// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7b947833d2a6e6bc "nitro (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Grain } from "./chunks/chunk-J6FBOBB4.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-KQJZ5C44.js";
import { Icon } from "./chunks/chunk-KD6F3UC3.js";
import { className, css, fonts } from "./chunks/chunk-EGECXSOW.js";
import "./chunks/chunk-HR56UER2.js";
import { routes } from "./chunks/chunk-UZPGWJTJ.js";

// virtual:blog-preview
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/xsuqUoppzYctg9fbtIs7/mIPj3hJvOe2HRvbPLrJY/LQV0S8Fun.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var GrainFonts = getFonts(Grain);
var MaterialFonts = getFonts(Icon);
var enabledGestures = {
	qF_jmFoJB: {
		hover: true,
	},
	QPONVA_fw: {
		hover: true,
	},
};
var cycleOrder = ["qF_jmFoJB", "QPONVA_fw"];
var serializationHash = "framer-k55WL";
var variantClassNames = {
	qF_jmFoJB: "framer-v-1e2sw08",
	QPONVA_fw: "framer-v-agyi3e",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.2,
	ease: [0.5, 0, 0.88, 0.77],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	desktop: "qF_jmFoJB",
	mobile: "QPONVA_fw",
};
var getProps = ({ date, height, id, image, link, title, width, ...props }) => {
	return {
		...props,
		BuEaurokH: date ?? props.BuEaurokH ?? "April, 22",
		F30Zfe44a: image ?? props.F30Zfe44a,
		gAn5f6CqK: link ?? props.gAn5f6CqK,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "qF_jmFoJB",
		YNKldBwuV:
			title ?? props.YNKldBwuV ?? "A friend in need is a friend indeed",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		F30Zfe44a,
		YNKldBwuV,
		BuEaurokH,
		gAn5f6CqK,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "qF_jmFoJB",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (gestureVariant === "QPONVA_fw-hover") return false;
		if (baseVariant === "QPONVA_fw") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={gAn5f6CqK}
						motionChild={true}
						nodeId={"qF_jmFoJB"}
						scopeId={"LQV0S8Fun"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1e2sw08", className3, classNames)} framer-1piq9af`}
							data-framer-name={"desktop"}
							layoutDependency={layoutDependency}
							layoutId={"qF_jmFoJB"}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"qF_jmFoJB-hover": {
										"data-framer-name": void 0,
									},
									"QPONVA_fw-hover": {
										"data-framer-name": void 0,
									},
									QPONVA_fw: {
										"data-framer-name": "mobile",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1c5cqmp"}
								layoutDependency={layoutDependency}
								layoutId={"OclFv84qa"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-ijaw8o"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"FpvF9NODx"}
									style={{
										"--extracted-a0htzi":
											"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={YNKldBwuV}
									variants={{
										"qF_jmFoJB-hover": {
											"--extracted-a0htzi":
												"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
										},
										"QPONVA_fw-hover": {
											"--extracted-a0htzi":
												"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"qF_jmFoJB-hover": {
												children: (
													<React.Fragment>
														<motion.h3
															className={"framer-styles-preset-12lj5ox"}
															data-styles-preset={"YckFIlg3V"}
															style={{
																"--framer-text-color":
																	"var(--extracted-a0htzi, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
															}}
														>
															{"A friend in need is a friend indeed"}
														</motion.h3>
													</React.Fragment>
												),
											},
											"QPONVA_fw-hover": {
												children: (
													<React.Fragment>
														<motion.h3
															className={"framer-styles-preset-12lj5ox"}
															data-styles-preset={"YckFIlg3V"}
															style={{
																"--framer-text-color":
																	"var(--extracted-a0htzi, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
															}}
														>
															{"A friend in need is a friend indeed"}
														</motion.h3>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.h3
											className={"framer-styles-preset-12lj5ox"}
											data-styles-preset={"YckFIlg3V"}
											style={{
												"--framer-text-color":
													"var(--extracted-a0htzi, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
											}}
										>
											{"A friend in need is a friend indeed"}
										</motion.h3>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1yah170"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"g5ooV_phr"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={BuEaurokH}
									variants={{
										"qF_jmFoJB-hover": {
											"--extracted-r6o4lv":
												"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
										},
										"QPONVA_fw-hover": {
											"--extracted-r6o4lv":
												"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"qF_jmFoJB-hover": {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1i4mbrj"}
															data-styles-preset={"s0y5Rymtd"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
															}}
														>
															{"April, 22"}
														</motion.p>
													</React.Fragment>
												),
											},
											"QPONVA_fw-hover": {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1i4mbrj"}
															data-styles-preset={"s0y5Rymtd"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
															}}
														>
															{"April, 22"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1i4mbrj"}
											data-styles-preset={"s0y5Rymtd"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25)))",
											}}
										>
											{"April, 22"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							{isDisplayed() && (
								<motion.div
									className={"framer-cnmmyp"}
									layoutDependency={layoutDependency}
									layoutId={"qyAvFDgng"}
								>
									<Image
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0 + -36,
											),
											sizes: `calc(max(${componentViewport?.width || "100vw"} / 4, 1px) * 0.502)`,
											...toResponsiveImage(F30Zfe44a),
										}}
										className={"framer-veamc8"}
										layoutDependency={layoutDependency}
										layoutId={"dwqMJVLAG"}
										style={{
											borderBottomLeftRadius: 2,
											borderBottomRightRadius: 2,
											borderTopLeftRadius: 2,
											borderTopRightRadius: 2,
											opacity: 0,
										}}
										variants={{
											"qF_jmFoJB-hover": {
												opacity: 1,
											},
										}}
									>
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-vebwzs-container"}
												isAuthoredByUser={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"pXMmFrKib-container"}
												nodeId={"pXMmFrKib"}
												rendersWithMotion={true}
												scopeId={"LQV0S8Fun"}
											>
												<Grain
													height={"100%"}
													id={"pXMmFrKib"}
													layoutId={"pXMmFrKib"}
													opacity={0.08}
													style={{
														height: "100%",
														width: "100%",
													}}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</Image>
								</motion.div>
							)}
							<motion.div
								className={"framer-1v8nzbe"}
								layoutDependency={layoutDependency}
								layoutId={"EKuI5AGCW"}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-az5jpw-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"qXN46gXTl-container"}
										nodeId={"qXN46gXTl"}
										rendersWithMotion={true}
										scopeId={"LQV0S8Fun"}
										style={{
											rotate: -45,
										}}
										variants={{
											"qF_jmFoJB-hover": {
												rotate: 0,
											},
											"QPONVA_fw-hover": {
												rotate: 0,
											},
										}}
									>
										<Icon
											color={
												"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))"
											}
											height={"100%"}
											iconSearch={"Home"}
											iconSelection={"ArrowForward"}
											iconStyle15={"Filled"}
											iconStyle2={"Filled"}
											iconStyle7={"Filled"}
											id={"qXN46gXTl"}
											layoutId={"qXN46gXTl"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											width={"100%"}
											{...addPropertyOverrides(
												{
													"qF_jmFoJB-hover": {
														color:
															"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
													},
													"QPONVA_fw-hover": {
														color:
															"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-k55WL.framer-1piq9af, .framer-k55WL .framer-1piq9af { display: block; }",
	".framer-k55WL.framer-1e2sw08 { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 1020px; }",
	".framer-k55WL .framer-1c5cqmp { align-content: center; align-items: center; display: flex; flex: 2 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-k55WL .framer-ijaw8o { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-k55WL .framer-1yah170 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-k55WL .framer-cnmmyp { align-self: stretch; flex: 1 0 0px; height: auto; overflow: visible; position: relative; width: 1px; }",
	".framer-k55WL .framer-veamc8 { bottom: -36px; flex: none; left: 0px; overflow: visible; position: absolute; top: -36px; width: 50%; }",
	".framer-k55WL .framer-vebwzs-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; }",
	".framer-k55WL .framer-1v8nzbe { align-self: stretch; flex: 1 0 0px; gap: 10px; height: auto; overflow: visible; position: relative; width: 1px; }",
	".framer-k55WL .framer-az5jpw-container { flex: none; height: 36px; position: absolute; right: -10px; top: -10px; width: 36px; }",
	".framer-k55WL.framer-v-agyi3e.framer-1e2sw08 { width: 444px; }",
	".framer-k55WL.framer-v-agyi3e .framer-1c5cqmp { flex: 3 0 0px; }",
	".framer-k55WL.framer-v-agyi3e .framer-az5jpw-container { height: 24px; right: -6px; top: 4px; width: 24px; }",
	".framer-k55WL.framer-v-1e2sw08.hover .framer-veamc8 { left: unset; right: 0px; }",
	...css2,
	...css,
];
var FramerLQV0S8Fun = withCSS(Component, css3, "framer-k55WL");
var stdin_default = FramerLQV0S8Fun;
FramerLQV0S8Fun.displayName = "Blog Preview";
FramerLQV0S8Fun.defaultProps = {
	height: 85.5,
	width: 1020,
};
addPropertyControls(FramerLQV0S8Fun, {
	variant: {
		options: ["qF_jmFoJB", "QPONVA_fw"],
		optionTitles: ["desktop", "mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	F30Zfe44a: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	YNKldBwuV: {
		defaultValue: "A friend in need is a friend indeed",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	BuEaurokH: {
		defaultValue: "April, 22",
		displayTextArea: false,
		title: "date",
		type: ControlType.String,
	},
	gAn5f6CqK: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerLQV0S8Fun,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...GrainFonts,
		...MaterialFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:blog-preview
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "QPONVA_fw",
	xl: "qF_jmFoJB",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BlogPreviewFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var blog_preview_default = ComponentWithRoot;
export { blog_preview_default as default };
