// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7b947833d2a6e6bc "nitro (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Active' | 'Inactive' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-UZPGWJTJ.js";

// virtual:bullet-selector
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/kHu1lXIAUNDnC1YJKa7l/2rdnKNA86OVh4vwY08sl/W4z9cbC0Y.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion } from "unframer";
import * as React from "react";
var cycleOrder = ["bq6HknN3R", "SHaao7P84"];
var variantClassNames = {
	bq6HknN3R: "framer-v-17ktq1m",
	SHaao7P84: "framer-v-7zfj31",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var humanReadableVariantMap = {
	Active: "bq6HknN3R",
	Inactive: "SHaao7P84",
};
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		duration: 0.3,
		ease: [0.44, 0, 0.56, 1],
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Component = /* @__PURE__ */ React.forwardRef(function (
	{
		id,
		style,
		className,
		width,
		height,
		layoutId,
		variant: outerVariant = "bq6HknN3R",
		...restProps
	},
	ref,
) {
	const outerVariantId = humanReadableVariantMap[outerVariant];
	const variant = outerVariantId || outerVariant;
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "bq6HknN3R",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = variants.join("-") + restProps.layoutDependency;
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx("framer-68D4C", classNames)}
				style={{
					display: "contents",
				}}
			>
				<motion.div
					{...restProps}
					className={cx("framer-17ktq1m", className)}
					data-framer-name={"Active"}
					layoutDependency={layoutDependency}
					layoutId={"bq6HknN3R"}
					ref={ref}
					style={{
						backgroundColor: "rgb(22, 22, 24)",
						borderBottomLeftRadius: 16,
						borderBottomRightRadius: 16,
						borderTopLeftRadius: 16,
						borderTopRightRadius: 16,
						opacity: 1,
						...style,
					}}
					transition={transition}
					variants={{
						SHaao7P84: {
							backgroundColor:
								"var(--token-eada6075-df84-4c9f-9fba-107a6537bba4, rgba(18, 18, 23, 0.75))",
							opacity: 0.25,
						},
					}}
					{...addPropertyOverrides(
						{
							SHaao7P84: {
								"data-framer-name": "Inactive",
							},
						},
						baseVariant,
						gestureVariant,
					)}
				/>
			</motion.div>
		</LayoutGroup>
	);
});
var css = [
	'.framer-68D4C [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-68D4C .framer-u9u0w8 { display: block; }",
	".framer-68D4C .framer-17ktq1m { height: 4px; overflow: visible; position: relative; width: 4px; }",
];
var FramerW4z9cbC0Y = withCSS(Component, css, "framer-68D4C");
var stdin_default = FramerW4z9cbC0Y;
FramerW4z9cbC0Y.displayName = "Bullet Selector";
FramerW4z9cbC0Y.defaultProps = {
	height: 4,
	width: 4,
};
addPropertyControls(FramerW4z9cbC0Y, {
	variant: {
		options: ["bq6HknN3R", "SHaao7P84"],
		optionTitles: ["Active", "Inactive"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(FramerW4z9cbC0Y, []);

// virtual:bullet-selector
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BulletSelectorFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var bullet_selector_default = ComponentWithRoot;
export { bullet_selector_default as default };
