// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7b947833d2a6e6bc "nitro (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'desktop' | 'laptop' | 'tablet' | 'mobile' // Variant
 * background?: string // Background
 * textColor?: string // Text Color
 * title?: string // Title
 * category?: string // Category
 * amount?: string // Amount
 * link?: string // Link
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */
import { Icon } from "./chunks/chunk-KD6F3UC3.js";
import "./chunks/chunk-HR56UER2.js";
import { routes } from "./chunks/chunk-UZPGWJTJ.js";

// virtual:card-2
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/2qNeBybfF3KCQDPABOT8/MLgdheH5Ia6QyT1QCt75/Gt72hD3Ij.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MaterialFonts = getFonts(Icon);
var enabledGestures = {
	neXAabI55: {
		hover: true,
	},
	pMssQbQSQ: {
		hover: true,
	},
	RNAwIFFuo: {
		hover: true,
	},
	xJt8ugs_T: {
		hover: true,
	},
};
var cycleOrder = ["xJt8ugs_T", "RNAwIFFuo", "pMssQbQSQ", "neXAabI55"];
var serializationHash = "framer-X8KQ3";
var variantClassNames = {
	neXAabI55: "framer-v-h1debz",
	pMssQbQSQ: "framer-v-1b5i4go",
	RNAwIFFuo: "framer-v-1ejgm9r",
	xJt8ugs_T: "framer-v-q7s7b5",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	desktop: "xJt8ugs_T",
	laptop: "RNAwIFFuo",
	mobile: "neXAabI55",
	tablet: "pMssQbQSQ",
};
var getProps = ({
	amount,
	background,
	category,
	height,
	id,
	image,
	link,
	textColor,
	title,
	width,
	...props
}) => {
	return {
		...props,
		enyQTFGl5: background ?? props.enyQTFGl5 ?? "rgb(238, 255, 0)",
		HNdJyx_ZD: link ?? props.HNdJyx_ZD,
		lSB3XNzQs: category ?? props.lSB3XNzQs ?? "Branding and identity",
		MUlgyJEIg: textColor ?? props.MUlgyJEIg ?? "rgb(0, 0, 0)",
		N2NdkcDAy: image ?? props.N2NdkcDAy,
		POe5RX9yr: amount ?? props.POe5RX9yr ?? "2023",
		v4nQNdbNw: title ?? props.v4nQNdbNw ?? "Project Name",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "xJt8ugs_T",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		enyQTFGl5,
		MUlgyJEIg,
		v4nQNdbNw,
		lSB3XNzQs,
		POe5RX9yr,
		HNdJyx_ZD,
		N2NdkcDAy,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "xJt8ugs_T",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={HNdJyx_ZD}
						motionChild={true}
						nodeId={"xJt8ugs_T"}
						scopeId={"Gt72hD3Ij"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-q7s7b5", className, classNames)} framer-8udmcf`}
							data-border={true}
							data-framer-name={"desktop"}
							layoutDependency={layoutDependency}
							layoutId={"xJt8ugs_T"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-9b54e130-a21e-4df7-b158-707338e41ccb, rgba(255, 255, 255, 0.1))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor: enyQTFGl5,
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
								boxShadow:
									"0px -4.031050927634351px 20.155254638171755px -0.3125px rgba(0, 0, 0, 0.08), 0px -9.554302482283674px 47.77151241141837px -0.625px rgba(0, 0, 0, 0.08), 0px -17.42803531035315px 87.14017655176575px -0.9375px rgba(0, 0, 0, 0.08), 0px -28.974073717254214px 144.87036858627107px -1.25px rgba(0, 0, 0, 0.08), 0px -46.790766532695855px 233.95383266347926px -1.5625px rgba(0, 0, 0, 0.08), 0px -76.59184225781354px 382.9592112890677px -1.875px rgba(0, 0, 0, 0.08), 0px -131.88598023208323px 659.4299011604162px -2.1875px rgba(0, 0, 0, 0.08), 0px -240px 1200px -2.5px rgba(0, 0, 0, 0.08)",
								...style,
							}}
							{...addPropertyOverrides(
								{
									"neXAabI55-hover": {
										"data-framer-name": void 0,
									},
									"pMssQbQSQ-hover": {
										"data-framer-name": void 0,
									},
									"RNAwIFFuo-hover": {
										"data-framer-name": void 0,
									},
									"xJt8ugs_T-hover": {
										"data-framer-name": void 0,
									},
									neXAabI55: {
										"data-framer-name": "mobile",
									},
									pMssQbQSQ: {
										"data-framer-name": "tablet",
									},
									RNAwIFFuo: {
										"data-framer-name": "laptop",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-wm6bzz"}
								layoutDependency={layoutDependency}
								layoutId={"h7FT7k2Nk"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-whxn3l"}
									fonts={["GF;DM Mono-300"]}
									layoutDependency={layoutDependency}
									layoutId={"ClFQseUJj"}
									style={{
										"--extracted-r6o4lv":
											"var(--variable-reference-MUlgyJEIg-Gt72hD3Ij)",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										"--framer-paragraph-spacing": "0px",
										"--variable-reference-MUlgyJEIg-Gt72hD3Ij": MUlgyJEIg,
									}}
									text={POe5RX9yr}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "R0Y7RE0gTW9uby0zMDA=",
												"--framer-font-family": '"DM Mono", monospace',
												"--framer-font-size": "14px",
												"--framer-font-weight": "300",
												"--framer-letter-spacing": "0px",
												"--framer-line-height": "1em",
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--variable-reference-MUlgyJEIg-Gt72hD3Ij))",
											}}
										>
											{"2023"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-ufclh9"}
									fonts={["GF;DM Mono-300"]}
									layoutDependency={layoutDependency}
									layoutId={"m78vQToGm"}
									style={{
										"--extracted-r6o4lv":
											"var(--variable-reference-MUlgyJEIg-Gt72hD3Ij)",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										"--framer-paragraph-spacing": "0px",
										"--variable-reference-MUlgyJEIg-Gt72hD3Ij": MUlgyJEIg,
									}}
									text={lSB3XNzQs}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "R0Y7RE0gTW9uby0zMDA=",
												"--framer-font-family": '"DM Mono", monospace',
												"--framer-font-size": "14px",
												"--framer-font-weight": "300",
												"--framer-letter-spacing": "0px",
												"--framer-line-height": "1em",
												"--framer-text-alignment": "right",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--variable-reference-MUlgyJEIg-Gt72hD3Ij))",
											}}
										>
											{"Branding and identity"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-r1lcrp"}
								layoutDependency={layoutDependency}
								layoutId={"Dc5AFKc0H"}
								style={{
									backgroundColor: MUlgyJEIg,
									opacity: 0.25,
								}}
							/>
							<motion.div
								className={"framer-11euqg4"}
								layoutDependency={layoutDependency}
								layoutId={"D9NnArhZr"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1wzzv9z"}
									fonts={["GF;Manrope-500"]}
									layoutDependency={layoutDependency}
									layoutId={"raiMr6PS_"}
									style={{
										"--extracted-1of0zx5":
											"var(--variable-reference-MUlgyJEIg-Gt72hD3Ij)",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										"--framer-paragraph-spacing": "0px",
										"--variable-reference-MUlgyJEIg-Gt72hD3Ij": MUlgyJEIg,
									}}
									text={v4nQNdbNw}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h2
											style={{
												"--font-selector": "R0Y7TWFucm9wZS01MDA=",
												"--framer-font-family":
													'"Manrope", "Manrope Placeholder", sans-serif',
												"--framer-font-size": "64px",
												"--framer-font-weight": "500",
												"--framer-letter-spacing": "-2.7px",
												"--framer-line-height": "1.35em",
												"--framer-text-color":
													"var(--extracted-1of0zx5, var(--variable-reference-MUlgyJEIg-Gt72hD3Ij))",
											}}
										>
											{"Project Name"}
										</motion.h2>
									</React.Fragment>
								</RichText>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-a1v4om-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"NuZ5LKYi7-container"}
										nodeId={"NuZ5LKYi7"}
										rendersWithMotion={true}
										scopeId={"Gt72hD3Ij"}
										style={{
											rotate: 0,
										}}
										variants={{
											"neXAabI55-hover": {
												rotate: -45,
											},
											"pMssQbQSQ-hover": {
												rotate: -45,
											},
											"RNAwIFFuo-hover": {
												rotate: -45,
											},
											"xJt8ugs_T-hover": {
												rotate: -45,
											},
										}}
									>
										<Icon
											color={MUlgyJEIg}
											height={"100%"}
											iconSearch={"Home"}
											iconSelection={"ArrowForward"}
											iconStyle15={"Filled"}
											iconStyle2={"Filled"}
											iconStyle7={"Filled"}
											id={"NuZ5LKYi7"}
											layoutId={"NuZ5LKYi7"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) + 24 + 181.4,
									),
									sizes: `calc(${componentViewport?.width || "100vw"} - 48px)`,
									...toResponsiveImage(N2NdkcDAy),
								}}
								className={"framer-ewccef"}
								layoutDependency={layoutDependency}
								layoutId={"k5GyW5VI8"}
								{...addPropertyOverrides(
									{
										neXAabI55: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 12 + 181.4,
												),
												sizes: `calc(${componentViewport?.width || "100vw"} - 24px)`,
												...toResponsiveImage(N2NdkcDAy),
											},
										},
										pMssQbQSQ: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 16 + 181.4,
												),
												sizes: `calc(${componentViewport?.width || "100vw"} - 32px)`,
												...toResponsiveImage(N2NdkcDAy),
											},
										},
										RNAwIFFuo: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 20 + 181.4,
												),
												sizes: `calc(${componentViewport?.width || "100vw"} - 40px)`,
												...toResponsiveImage(N2NdkcDAy),
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-X8KQ3.framer-8udmcf, .framer-X8KQ3 .framer-8udmcf { display: block; }",
	".framer-X8KQ3.framer-q7s7b5 { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: 526px; justify-content: flex-start; overflow: hidden; padding: 24px; position: relative; text-decoration: none; width: 1920px; will-change: var(--framer-will-change-override, transform); }",
	".framer-X8KQ3 .framer-wm6bzz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-X8KQ3 .framer-whxn3l { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-X8KQ3 .framer-ufclh9, .framer-X8KQ3 .framer-1wzzv9z { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-X8KQ3 .framer-r1lcrp { flex: none; height: 1px; overflow: visible; position: relative; width: 100%; }",
	".framer-X8KQ3 .framer-11euqg4 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-X8KQ3 .framer-a1v4om-container { flex: none; height: 72px; position: relative; width: 72px; }",
	".framer-X8KQ3 .framer-ewccef { flex: 1 0 0px; height: 1px; overflow: visible; position: relative; width: 100%; }",
	".framer-X8KQ3.framer-v-1ejgm9r.framer-q7s7b5 { padding: 20px; width: 989px; }",
	".framer-X8KQ3.framer-v-1ejgm9r .framer-a1v4om-container { height: 48px; width: 48px; }",
	".framer-X8KQ3.framer-v-1b5i4go.framer-q7s7b5 { padding: 16px; width: 810px; }",
	".framer-X8KQ3.framer-v-1b5i4go .framer-a1v4om-container { height: 36px; width: 36px; }",
	".framer-X8KQ3.framer-v-h1debz.framer-q7s7b5 { padding: 12px; width: 390px; }",
	".framer-X8KQ3.framer-v-h1debz .framer-a1v4om-container { height: 32px; width: 32px; }",
	'.framer-X8KQ3[data-border="true"]::after, .framer-X8KQ3 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerGt72hD3Ij = withCSS(Component, css, "framer-X8KQ3");
var stdin_default = FramerGt72hD3Ij;
FramerGt72hD3Ij.displayName = "Card 2";
FramerGt72hD3Ij.defaultProps = {
	height: 526,
	width: 1920,
};
addPropertyControls(FramerGt72hD3Ij, {
	variant: {
		options: ["xJt8ugs_T", "RNAwIFFuo", "pMssQbQSQ", "neXAabI55"],
		optionTitles: ["desktop", "laptop", "tablet", "mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	enyQTFGl5: {
		defaultValue: "rgb(238, 255, 0)",
		title: "Background",
		type: ControlType.Color,
	},
	MUlgyJEIg: {
		defaultValue: "rgb(0, 0, 0)",
		title: "Text Color",
		type: ControlType.Color,
	},
	v4nQNdbNw: {
		defaultValue: "Project Name",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	lSB3XNzQs: {
		defaultValue: "Branding and identity",
		displayTextArea: false,
		title: "Category",
		type: ControlType.String,
	},
	POe5RX9yr: {
		defaultValue: "2023",
		displayTextArea: false,
		title: "Amount",
		type: ControlType.String,
	},
	HNdJyx_ZD: {
		title: "Link",
		type: ControlType.Link,
	},
	N2NdkcDAy: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerGt72hD3Ij,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "DM Mono",
					source: "google",
					style: "normal",
					uiFamilyName: "DM Mono",
					url: "https://fonts.gstatic.com/s/dmmono/v16/aFTR7PB1QTsUX8KYvrGyIYGnbKX9Rlk.woff2",
					weight: "300",
				},
				{
					cssFamilyName: "Manrope",
					source: "google",
					style: "normal",
					uiFamilyName: "Manrope",
					url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk7PFO_A87jxeN7B.woff2",
					weight: "500",
				},
			],
		},
		...MaterialFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:card-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "neXAabI55",
	md: "pMssQbQSQ",
	lg: "RNAwIFFuo",
	xl: "xJt8ugs_T",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Card2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var card_2_default = ComponentWithRoot;
export { card_2_default as default };
