// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7b947833d2a6e6bc "nitro (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // title
 * color?: string // Color
 * value?: string // value
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-FCJZKTDO.js";
import { className, css, fonts } from "./chunks/chunk-EGECXSOW.js";
import { routes } from "./chunks/chunk-UZPGWJTJ.js";

// virtual:case-data
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/qldoXFIcwlqrdFMk8RC7/S02aWJrBIzXHwaKHpwic/ESWUn1Zm2.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-KejSH";
var variantClassNames = {
	m4nxPnp6J: "framer-v-a6mm7d",
};
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ color, height, id, title, value, width, ...props }) => {
	return {
		...props,
		dfBpIV9q8: title ?? props.dfBpIV9q8 ?? "title",
		I3V9wrY_B: color ?? props.I3V9wrY_B ?? "rgb(0, 0, 0)",
		PeFNZ6IHm: value ?? props.PeFNZ6IHm ?? "value",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		dfBpIV9q8,
		I3V9wrY_B,
		PeFNZ6IHm,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "m4nxPnp6J",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-a6mm7d",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"m4nxPnp6J"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<motion.div
							className={"framer-kn0ydk"}
							data-framer-name={"Tagline"}
							layoutDependency={layoutDependency}
							layoutId={"pBxwwaOdb"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-tll1vd"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"TLdW2o0Wq"}
								style={{
									"--extracted-r6o4lv":
										"var(--variable-reference-I3V9wrY_B-ESWUn1Zm2)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									"--variable-reference-I3V9wrY_B-ESWUn1Zm2": I3V9wrY_B,
									opacity: 0.75,
								}}
								text={dfBpIV9q8}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1i4mbrj"}
										data-styles-preset={"s0y5Rymtd"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--variable-reference-I3V9wrY_B-ESWUn1Zm2))",
										}}
									>
										{"title"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-9n1a1t"}
								layoutDependency={layoutDependency}
								layoutId={"HTVokzBNk"}
								style={{
									backgroundColor: I3V9wrY_B,
									opacity: 0.25,
								}}
							/>
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1ph5q1y"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"dzFZ_79sn"}
							style={{
								"--extracted-r6o4lv":
									"var(--variable-reference-I3V9wrY_B-ESWUn1Zm2)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
								"--variable-reference-I3V9wrY_B-ESWUn1Zm2": I3V9wrY_B,
							}}
							text={PeFNZ6IHm}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-ugcj2n"}
									data-styles-preset={"JLUy8CuLJ"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--variable-reference-I3V9wrY_B-ESWUn1Zm2))",
									}}
								>
									{"value"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-KejSH.framer-1a3n01f, .framer-KejSH .framer-1a3n01f { display: block; }",
	".framer-KejSH.framer-a6mm7d { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 252px; }",
	".framer-KejSH .framer-kn0ydk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-KejSH .framer-tll1vd { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-KejSH .framer-9n1a1t { flex: 1 0 0px; height: 1px; overflow: visible; position: relative; width: 1px; }",
	".framer-KejSH .framer-1ph5q1y { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css,
	...css2,
];
var FramerESWUn1Zm2 = withCSS(Component, css3, "framer-KejSH");
var stdin_default = FramerESWUn1Zm2;
FramerESWUn1Zm2.displayName = "case data";
FramerESWUn1Zm2.defaultProps = {
	height: 59,
	width: 252,
};
addPropertyControls(FramerESWUn1Zm2, {
	dfBpIV9q8: {
		defaultValue: "title",
		title: "title",
		type: ControlType.String,
	},
	I3V9wrY_B: {
		defaultValue: "rgb(0, 0, 0)",
		title: "Color",
		type: ControlType.Color,
	},
	PeFNZ6IHm: {
		defaultValue: "value",
		displayTextArea: false,
		title: "value",
		type: ControlType.String,
	},
});
addFonts(
	FramerESWUn1Zm2,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:case-data
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CaseDataFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var case_data_default = ComponentWithRoot;
export { case_data_default as default };
