// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7b947833d2a6e6bc "nitro (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'desktop' | 'mobile' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-2FJHF24R.js";
import { className, css, fonts } from "./chunks/chunk-G6UXAXIU.js";
import { Icon } from "./chunks/chunk-KD6F3UC3.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-EGECXSOW.js";
import "./chunks/chunk-HR56UER2.js";
import { routes } from "./chunks/chunk-UZPGWJTJ.js";

// virtual:cta
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/lN3pqDRfcrjbtyAkhhmP/CdvnewUZJlIZjv7CxOqD/CU3xNJ7B8.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	ResolveLinks,
	RichText as RichText2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useRouter,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/lHMn5wLP2aGtMGdG3w4N/3CZblg8dDzaLXhesRf8x/Z7putK0ON.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MaterialFonts = getFonts(Icon);
var enabledGestures = {
	M3mC5OGMA: {
		hover: true,
	},
};
var serializationHash = "framer-S7FGZ";
var variantClassNames = {
	M3mC5OGMA: "framer-v-1aqqjh1",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.1,
	ease: [0.5, 0, 0.88, 0.77],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, label, link, newTab, tap, width, ...props }) => {
	return {
		...props,
		EnfjDXQkn: newTab ?? props.EnfjDXQkn,
		VftTy7iTx: label ?? props.VftTy7iTx ?? "Button Label",
		y1IR6ulOD: tap ?? props.y1IR6ulOD,
		Z63mvCN3B: link ?? props.Z63mvCN3B,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		VftTy7iTx,
		Z63mvCN3B,
		y1IR6ulOD,
		EnfjDXQkn,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "M3mC5OGMA",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap2a90lm = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (y1IR6ulOD) {
			const res = await y1IR6ulOD(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={Z63mvCN3B}
						motionChild={true}
						nodeId={"M3mC5OGMA"}
						openInNewTab={EnfjDXQkn}
						scopeId={"Z7putK0ON"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1aqqjh1", className3, classNames)} framer-1hlbm9c`}
							data-border={true}
							data-framer-name={"M - Accent"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"M3mC5OGMA"}
							onTap={onTap2a90lm}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor: "rgba(0, 0, 0, 0)",
								...style,
							}}
							variants={{
								"M3mC5OGMA-hover": {
									"--border-color":
										"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
									backgroundColor: "rgb(22, 22, 24)",
								},
							}}
							{...addPropertyOverrides(
								{
									"M3mC5OGMA-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-ksjbcf"}
								data-framer-name={"bgfill"}
								layoutDependency={layoutDependency}
								layoutId={"kj1S7EtNJ"}
								style={{
									backgroundColor:
										"var(--token-90a64261-b816-47fc-8b95-db312dae9b11, rgba(255, 255, 255, 0))",
								}}
								variants={{
									"M3mC5OGMA-hover": {
										backgroundColor:
											"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
									},
								}}
							/>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1hzw3z"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Jm8FVWdji"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={VftTy7iTx}
								variants={{
									"M3mC5OGMA-hover": {
										"--extracted-r6o4lv":
											"var(--token-cd708a3c-25bb-4606-92f4-351c74f13945, rgb(0, 0, 0))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"M3mC5OGMA-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1i4mbrj"}
														data-styles-preset={"s0y5Rymtd"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-cd708a3c-25bb-4606-92f4-351c74f13945, rgb(0, 0, 0)))",
														}}
													>
														{"Button Label"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1i4mbrj"}
										data-styles-preset={"s0y5Rymtd"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
										}}
									>
										{"Button Label"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-361kkj"}
								data-framer-name={"Icon"}
								layoutDependency={layoutDependency}
								layoutId={"Qun8hATuj"}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-1crgkgq-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"w8Ezh4_TL-container"}
										nodeId={"w8Ezh4_TL"}
										rendersWithMotion={true}
										scopeId={"Z7putK0ON"}
										style={{
											rotate: -45,
										}}
										variants={{
											"M3mC5OGMA-hover": {
												rotate: 0,
											},
										}}
									>
										<Icon
											color={
												"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))"
											}
											height={"100%"}
											iconSearch={"Home"}
											iconSelection={"ArrowForward"}
											iconStyle15={"Filled"}
											iconStyle2={"Filled"}
											iconStyle7={"Filled"}
											id={"w8Ezh4_TL"}
											layoutId={"w8Ezh4_TL"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											width={"100%"}
											{...addPropertyOverrides(
												{
													"M3mC5OGMA-hover": {
														color:
															"var(--token-cd708a3c-25bb-4606-92f4-351c74f13945, rgb(0, 0, 0))",
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-S7FGZ.framer-1hlbm9c, .framer-S7FGZ .framer-1hlbm9c { display: block; }",
	".framer-S7FGZ.framer-1aqqjh1 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 16px 24px 16px 36px; position: relative; text-decoration: none; width: min-content; }",
	".framer-S7FGZ .framer-ksjbcf { bottom: -36px; flex: none; height: 36px; left: 0px; overflow: visible; position: absolute; right: 0px; z-index: 0; }",
	".framer-S7FGZ .framer-1hzw3z { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-S7FGZ .framer-361kkj { flex: none; gap: 0px; height: 20px; overflow: hidden; position: relative; width: 20px; }",
	".framer-S7FGZ .framer-1crgkgq-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; }",
	".framer-S7FGZ.framer-v-1aqqjh1.hover .framer-ksjbcf { bottom: 0px; height: unset; top: 0px; }",
	...css2,
	'.framer-S7FGZ[data-border="true"]::after, .framer-S7FGZ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerZ7putK0ON = withCSS(Component, css3, "framer-S7FGZ");
var stdin_default2 = FramerZ7putK0ON;
FramerZ7putK0ON.displayName = "Button";
FramerZ7putK0ON.defaultProps = {
	height: 52,
	width: 189,
};
addPropertyControls(FramerZ7putK0ON, {
	VftTy7iTx: {
		defaultValue: "Button Label",
		displayTextArea: false,
		title: "Label",
		type: ControlType.String,
	},
	Z63mvCN3B: {
		title: "Link",
		type: ControlType.Link,
	},
	y1IR6ulOD: {
		title: "Tap",
		type: ControlType.EventHandler,
	},
	EnfjDXQkn: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType.Boolean,
	},
});
addFonts(
	FramerZ7putK0ON,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...MaterialFonts,
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/lN3pqDRfcrjbtyAkhhmP/CdvnewUZJlIZjv7CxOqD/CU3xNJ7B8.js
var ButtonFonts = getFonts2(stdin_default2);
var AimFonts = getFonts2(stdin_default);
var cycleOrder = ["xV7AUf3kU", "QixkkqWov"];
var serializationHash2 = "framer-963qT";
var variantClassNames2 = {
	QixkkqWov: "framer-v-maw0dh",
	xV7AUf3kU: "framer-v-syn3b5",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	desktop: "xV7AUf3kU",
	mobile: "QixkkqWov",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "xV7AUf3kU",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "xV7AUf3kU",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "QixkkqWov") return false;
		return true;
	};
	const router = useRouter();
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-syn3b5",
							className3,
							classNames,
						)}
						data-framer-name={"desktop"}
						layoutDependency={layoutDependency}
						layoutId={"xV7AUf3kU"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								QixkkqWov: {
									"data-framer-name": "mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-gkfvri"}
							data-framer-name={"Tagline"}
							layoutDependency={layoutDependency}
							layoutId={"ov4NZOvcb"}
						>
							<RichText2
								__fromCanvasComponent={true}
								className={"framer-13mqwj5"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"q2PVOWo6S"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-1i4mbrj"}
										data-styles-preset={"s0y5Rymtd"}
									>
										{".say hello"}
									</motion2.p>
								</React2.Fragment>
							</RichText2>
							<motion2.div
								className={"framer-t4ju05"}
								layoutDependency={layoutDependency}
								layoutId={"S088OL9VD"}
								style={{
									backgroundColor:
										"var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25))",
								}}
							/>
						</motion2.div>
						<RichText2
							__fromCanvasComponent={true}
							className={"framer-1ijc0sv"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"bkXMX9OxQ"}
							style={{
								"--extracted-1of0zx5":
									"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React2.Fragment>
								<motion2.h2
									className={"framer-styles-preset-1wml6uu"}
									data-styles-preset={"fVxnimdqP"}
									style={{
										"--framer-text-color":
											"var(--extracted-1of0zx5, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
									}}
								>
									{
										"i'm open for freelance projects, feel free to  email me to see how can we collaborate"
									}
								</motion2.h2>
							</React2.Fragment>
						</RichText2>
						<motion2.div
							className={"framer-1tdxm2y"}
							data-framer-name={"Button Grid"}
							layoutDependency={layoutDependency}
							layoutId={"OXi14CObA"}
						>
							{isDisplayed() && (
								<motion2.div
									className={"framer-1ftqx64"}
									layoutDependency={layoutDependency}
									layoutId={"aZxBzbH8d"}
								/>
							)}
							<ResolveLinks
								links={[
									{
										href: {
											webPageId: "jQl8KobkC",
										},
										implicitPathVariables: void 0,
									},
									{
										href: {
											webPageId: "jQl8KobkC",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks) => (
									<ComponentViewportProvider2
										height={52}
										width={`max(${componentViewport?.width || "100vw"} / 4, 1px)`}
										y={(componentViewport?.y || 0) + 0 + 266 + 0}
										{...addPropertyOverrides2(
											{
												QixkkqWov: {
													width: `max(${componentViewport?.width || "100vw"} * 0.75, 1px)`,
													y: (componentViewport?.y || 0) + 0 + 202 + 0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer2
											className={"framer-1kc68j4-container"}
											layoutDependency={layoutDependency}
											layoutId={"d3YS6sAnI-container"}
											nodeId={"d3YS6sAnI"}
											rendersWithMotion={true}
											scopeId={"CU3xNJ7B8"}
										>
											{_jsx2(stdin_default2, {
												EnfjDXQkn: true,
												height: "100%",
												id: "d3YS6sAnI",
												layoutId: "d3YS6sAnI",
												style: {
													width: "100%",
												},
												VftTy7iTx: "contact me",
												width: "100%",
												Z63mvCN3B: resolvedLinks[0],
												...addPropertyOverrides2(
													{
														QixkkqWov: {
															Z63mvCN3B: resolvedLinks[1],
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer2>
									</ComponentViewportProvider2>
								)}
							</ResolveLinks>
							<motion2.div
								className={"framer-r4u9d0"}
								layoutDependency={layoutDependency}
								layoutId={"mcwcsJRlT"}
							>
								<ComponentViewportProvider2>
									<SmartComponentScopedContainer2
										className={"framer-1oq7rv1-container"}
										layoutDependency={layoutDependency}
										layoutId={"TnLzS4qZ5-container"}
										nodeId={"TnLzS4qZ5"}
										rendersWithMotion={true}
										scopeId={"CU3xNJ7B8"}
									>
										{_jsx2(stdin_default, {
											height: "100%",
											id: "TnLzS4qZ5",
											layoutId: "TnLzS4qZ5",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "YnXfrsvOD",
											width: "100%",
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
							</motion2.div>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-963qT.framer-1v1i1d0, .framer-963qT .framer-1v1i1d0 { display: block; }",
	".framer-963qT.framer-syn3b5 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1200px; }",
	".framer-963qT .framer-gkfvri { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-963qT .framer-13mqwj5 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-963qT .framer-t4ju05 { flex: 1 0 0px; height: 1px; overflow: hidden; position: relative; width: 1px; }",
	".framer-963qT .framer-1ijc0sv { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 75%; word-break: break-word; word-wrap: break-word; }",
	".framer-963qT .framer-1tdxm2y { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-963qT .framer-1ftqx64 { flex: 4 0 0px; height: 33px; overflow: hidden; position: relative; width: 1px; }",
	".framer-963qT .framer-1kc68j4-container { flex: 2 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-963qT .framer-r4u9d0 { align-self: stretch; flex: 2 0 0px; gap: 10px; height: auto; overflow: visible; position: relative; width: 1px; }",
	".framer-963qT .framer-1oq7rv1-container { bottom: 0px; flex: none; height: 36px; position: absolute; right: 0px; width: 36px; }",
	".framer-963qT.framer-v-maw0dh.framer-syn3b5 { gap: 48px; }",
	".framer-963qT.framer-v-maw0dh .framer-1kc68j4-container { flex: 3 0 0px; }",
	".framer-963qT.framer-v-maw0dh .framer-r4u9d0 { flex: 1 0 0px; }",
	...css2,
	...css,
];
var FramerCU3xNJ7B8 = withCSS2(Component2, css4, "framer-963qT");
var stdin_default3 = FramerCU3xNJ7B8;
FramerCU3xNJ7B8.displayName = "CTA";
FramerCU3xNJ7B8.defaultProps = {
	height: 491,
	width: 1200,
};
addPropertyControls2(FramerCU3xNJ7B8, {
	variant: {
		options: ["xV7AUf3kU", "QixkkqWov"],
		optionTitles: ["desktop", "mobile"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramerCU3xNJ7B8,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonFonts,
		...AimFonts,
		...getFontsFromSharedStyle2(fonts2),
		...getFontsFromSharedStyle2(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cta
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "QixkkqWov",
	xl: "xV7AUf3kU",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var cta_default = ComponentWithRoot;
export { cta_default as default };
