// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7b947833d2a6e6bc "nitro (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
}} Props

 */
import {
	className as className2,
	className2 as className3,
	css as css2,
	css2 as css3,
	fonts as fonts2,
	fonts2 as fonts3,
} from "./chunks/chunk-67WPTMYE.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-7JGR5MG2.js";
import { className, css, fonts } from "./chunks/chunk-FCJZKTDO.js";
import { Icon } from "./chunks/chunk-KD6F3UC3.js";
import "./chunks/chunk-HR56UER2.js";
import { routes } from "./chunks/chunk-UZPGWJTJ.js";

// virtual:footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/s9Wt1e2UaGTRhJzwQw1A/1a0a4H93HxhgMPSQojiG/FF7dljYBM.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	getFontsFromSharedStyle,
	Link as Link2,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext,
} from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/9EVMQeq3heGyM8onJK2d/ndRY7mF4x2D1MF2dpmOi/N7nh62B9F.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	getPropertyControls,
	Link,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion } from "unframer";
import * as React from "react";
var MaterialFonts = getFonts(Icon);
var MaterialControls = getPropertyControls(Icon);
var enabledGestures = {
	cR5H9c4Wb: {
		hover: true,
	},
};
var cycleOrder = ["cR5H9c4Wb"];
var variantClassNames = {
	cR5H9c4Wb: "framer-v-el8xql",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var humanReadableVariantMap = {};
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		duration: 0.3,
		ease: [0.44, 0, 0.56, 1],
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Component = /* @__PURE__ */ React.forwardRef(function (
	{
		id,
		style,
		className: className5,
		width,
		height,
		layoutId,
		variant: outerVariant = "cR5H9c4Wb",
		icon: Ga4XD6inS = "Twitter",
		link: n98VOgYIP,
		...restProps
	},
	ref,
) {
	const outerVariantId = humanReadableVariantMap[outerVariant];
	const variant = outerVariantId || outerVariant;
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "cR5H9c4Wb",
		enabledGestures,
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = variants.join("-") + restProps.layoutDependency;
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx("framer-PDnFr", classNames)}
				style={{
					display: "contents",
				}}
			>
				<Link href={n98VOgYIP} openInNewTab={true}>
					<motion.a
						{...restProps}
						className={`${cx("framer-el8xql", className5)} framer-a0qk21`}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"cR5H9c4Wb"}
						ref={ref}
						style={{
							...style,
						}}
						transition={transition}
						{...addPropertyOverrides(
							{
								"cR5H9c4Wb-hover": {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-qri5vk-container"}
							layoutDependency={layoutDependency}
							layoutId={"JS0g1KcqQ-container"}
							transition={transition}
						>
							<Icon
								color={
									'var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25)) /* {"name":"white 25"} */'
								}
								height={"100%"}
								iconSearch={"Home"}
								iconSelection={Ga4XD6inS}
								iconStyle15={"Filled"}
								iconStyle2={"Filled"}
								iconStyle7={"Filled"}
								id={"JS0g1KcqQ"}
								layoutId={"JS0g1KcqQ"}
								mirrored={false}
								selectByList={true}
								style={{
									height: "100%",
									width: "100%",
								}}
								width={"100%"}
								{...addPropertyOverrides(
									{
										"cR5H9c4Wb-hover": {
											color:
												'var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)) /* {"name":"white 100"} */',
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</motion.div>
					</motion.a>
				</Link>
			</motion.div>
		</LayoutGroup>
	);
});
var css5 = [
	'.framer-PDnFr [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-PDnFr .framer-a0qk21 { display: block; }",
	".framer-PDnFr .framer-el8xql { height: 24px; overflow: hidden; position: relative; text-decoration: none; width: 24px; }",
	".framer-PDnFr .framer-qri5vk-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; }",
	".framer-PDnFr .framer-v-el8xql .framer-el8xql { cursor: pointer; }",
];
var FramerN7nh62B9F = withCSS(Component, css5, "framer-PDnFr");
var stdin_default = FramerN7nh62B9F;
FramerN7nh62B9F.displayName = "Social";
FramerN7nh62B9F.defaultProps = {
	height: 24,
	width: 24,
};
addPropertyControls(FramerN7nh62B9F, {
	Ga4XD6inS: (MaterialControls === null || MaterialControls === void 0
		? void 0
		: MaterialControls["iconSelection"]) && {
		...MaterialControls["iconSelection"],
		defaultValue: "Twitter",
		hidden: void 0,
		title: "Icon",
	},
	n98VOgYIP: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(FramerN7nh62B9F, [...MaterialFonts]);

// /:https://framerusercontent.com/modules/s9Wt1e2UaGTRhJzwQw1A/1a0a4H93HxhgMPSQojiG/FF7dljYBM.js
var SocialFonts = getFonts2(stdin_default);
var MotionDivWithFX = withFX(motion2.div);
var cycleOrder2 = ["jrG4uFPXX", "rm3kfWLuK"];
var serializationHash = "framer-S5xC9";
var variantClassNames2 = {
	jrG4uFPXX: "framer-v-dxiozy",
	rm3kfWLuK: "framer-v-1o9e6lw",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Variant 1": "jrG4uFPXX",
	"Variant 2": "rm3kfWLuK",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "jrG4uFPXX",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "jrG4uFPXX",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2, className4, className3];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__spring={{
							damping: 60,
							delay: 0,
							duration: 0.3,
							ease: [0.44, 0, 0.56, 1],
							mass: 1,
							stagger: 0,
							stiffness: 500,
							type: "spring",
						}}
						__framer__styleTransformEffectEnabled={true}
						__framer__transformTargets={[
							{
								target: {
									opacity: 0,
									rotate: 0,
									rotateX: 0,
									rotateY: 0,
									scale: 1,
									skewX: 0,
									skewY: 0,
									x: 0,
									y: -120,
								},
							},
							{
								target: {
									opacity: 1,
									rotate: 0,
									rotateX: 0,
									rotateY: 0,
									scale: 1,
									skewX: 0,
									skewY: 0,
									x: 0,
									y: 0,
								},
							},
						]}
						__framer__transformTrigger={"onInView"}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx2(
							scopingClassNames,
							"framer-dxiozy",
							className5,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"jrG4uFPXX"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								rm3kfWLuK: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-cb3dtg"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"uTIhPE1wG"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides2(
								{
									rm3kfWLuK: {
										children: (
											<React2.Fragment>
												<motion2.p
													className={"framer-styles-preset-ugcj2n"}
													data-styles-preset={"JLUy8CuLJ"}
													style={{
														"--framer-text-alignment": "center",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
													}}
												>
													<Link2
														href={"https://easyfast.design"}
														motionChild={true}
														nodeId={"uTIhPE1wG"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"FF7dljYBM"}
														smoothScroll={false}
													>
														<motion2.a
															className={"framer-styles-preset-1wicq5s"}
															data-styles-preset={"ro7OPezbn"}
														>
															{"easyfast.design"}
														</motion2.a>
													</Link2>
												</motion2.p>
											</React2.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React2.Fragment>
								<motion2.p
									className={"framer-styles-preset-ugcj2n"}
									data-styles-preset={"JLUy8CuLJ"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
									}}
								>
									<Link2
										href={"https://easyfast.design"}
										motionChild={true}
										nodeId={"uTIhPE1wG"}
										openInNewTab={false}
										relValues={[]}
										scopeId={"FF7dljYBM"}
										smoothScroll={false}
									>
										<motion2.a
											className={"framer-styles-preset-1wicq5s"}
											data-styles-preset={"ro7OPezbn"}
										>
											{"easyfast.design"}
										</motion2.a>
									</Link2>
								</motion2.p>
							</React2.Fragment>
						</RichText>
						<motion2.div
							className={"framer-2fbv7s"}
							data-framer-name={"Links"}
							layoutDependency={layoutDependency}
							layoutId={"gw_8YBsqs"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-tn4v4g"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"MwuwifQ7K"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-21ogod"}
										data-styles-preset={"xZndidUCt"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
										}}
									>
										<Link2
											href={{
												webPageId: "xaVhC_xTq",
											}}
											motionChild={true}
											nodeId={"MwuwifQ7K"}
											openInNewTab={false}
											relValues={[]}
											scopeId={"FF7dljYBM"}
											smoothScroll={false}
										>
											<motion2.a
												className={"framer-styles-preset-1wicq5s"}
												data-styles-preset={"ro7OPezbn"}
											>
												{"projects"}
											</motion2.a>
										</Link2>
									</motion2.p>
								</React2.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1hnstsk"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"K4zbfSiGm"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-21ogod"}
										data-styles-preset={"xZndidUCt"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
										}}
									>
										<Link2
											href={{
												webPageId: "BQxSXX7Vv",
											}}
											motionChild={true}
											nodeId={"K4zbfSiGm"}
											openInNewTab={false}
											relValues={[]}
											scopeId={"FF7dljYBM"}
											smoothScroll={false}
										>
											<motion2.a
												className={"framer-styles-preset-1wicq5s"}
												data-styles-preset={"ro7OPezbn"}
											>
												{"about"}
											</motion2.a>
										</Link2>
									</motion2.p>
								</React2.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-mbjo5"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"VQC6Vwu4o"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-21ogod"}
										data-styles-preset={"xZndidUCt"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
										}}
									>
										<Link2
											href={{
												webPageId: "ElzBhd0WH",
											}}
											motionChild={true}
											nodeId={"VQC6Vwu4o"}
											openInNewTab={false}
											relValues={[]}
											scopeId={"FF7dljYBM"}
											smoothScroll={false}
										>
											<motion2.a
												className={"framer-styles-preset-1wicq5s"}
												data-styles-preset={"ro7OPezbn"}
											>
												{"notes"}
											</motion2.a>
										</Link2>
									</motion2.p>
								</React2.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-v1xmb4"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"jbieRkSQ0"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-21ogod"}
										data-styles-preset={"xZndidUCt"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
										}}
									>
										<Link2
											href={{
												webPageId: "jQl8KobkC",
											}}
											motionChild={true}
											nodeId={"jbieRkSQ0"}
											openInNewTab={false}
											relValues={[]}
											scopeId={"FF7dljYBM"}
											smoothScroll={false}
										>
											<motion2.a
												className={"framer-styles-preset-1wicq5s"}
												data-styles-preset={"ro7OPezbn"}
											>
												{"contact"}
											</motion2.a>
										</Link2>
									</motion2.p>
								</React2.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-n6nxmj"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"ThZYI9uyF"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-21ogod"}
										data-styles-preset={"xZndidUCt"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
										}}
									>
										<Link2
											href={"https://framer.link/MvMdlCP"}
											motionChild={true}
											nodeId={"ThZYI9uyF"}
											openInNewTab={true}
											relValues={[]}
											scopeId={"FF7dljYBM"}
											smoothScroll={false}
										>
											<motion2.a
												className={"framer-styles-preset-6hy7sq"}
												data-styles-preset={"xSmbUc6JM"}
											>
												{"get template"}
											</motion2.a>
										</Link2>
									</motion2.p>
								</React2.Fragment>
							</RichText>
						</motion2.div>
						<motion2.div
							className={"framer-1lm36gk"}
							data-framer-name={"Socials"}
							layoutDependency={layoutDependency}
							layoutId={"YZRJrwWL9"}
						>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-1hireqr-container"}
									layoutDependency={layoutDependency}
									layoutId={"WbycpyIB7-container"}
									nodeId={"WbycpyIB7"}
									rendersWithMotion={true}
									scopeId={"FF7dljYBM"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										icon: "YouTube",
										id: "WbycpyIB7",
										layoutId: "WbycpyIB7",
										link: "youtube.com",
										style: {
											height: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-cg201q-container"}
									layoutDependency={layoutDependency}
									layoutId={"IDmikDZEw-container"}
									nodeId={"IDmikDZEw"}
									rendersWithMotion={true}
									scopeId={"FF7dljYBM"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										icon: "Twitter",
										id: "IDmikDZEw",
										layoutId: "IDmikDZEw",
										link: "twitter.com/stfnco",
										style: {
											height: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-811ryh-container"}
									layoutDependency={layoutDependency}
									layoutId={"oNs4qpprf-container"}
									nodeId={"oNs4qpprf"}
									rendersWithMotion={true}
									scopeId={"FF7dljYBM"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										icon: "Instagram",
										id: "oNs4qpprf",
										layoutId: "oNs4qpprf",
										link: "instagram.com",
										style: {
											height: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion2.div>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup2>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-S5xC9.framer-v0uh11, .framer-S5xC9 .framer-v0uh11 { display: block; }",
	".framer-S5xC9.framer-dxiozy { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 100px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
	".framer-S5xC9 .framer-cb3dtg { flex: 1 0 0px; height: auto; max-width: 1920px; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-S5xC9 .framer-2fbv7s { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 36px; height: 100%; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-S5xC9 .framer-tn4v4g, .framer-S5xC9 .framer-1hnstsk, .framer-S5xC9 .framer-mbjo5, .framer-S5xC9 .framer-v1xmb4, .framer-S5xC9 .framer-n6nxmj { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-S5xC9 .framer-1lm36gk { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: 100%; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-S5xC9 .framer-1hireqr-container, .framer-S5xC9 .framer-cg201q-container, .framer-S5xC9 .framer-811ryh-container { flex: none; height: 24px; position: relative; width: 24px; }",
	".framer-S5xC9.framer-v-1o9e6lw.framer-dxiozy { flex-direction: column; gap: 52px; height: min-content; }",
	".framer-S5xC9.framer-v-1o9e6lw .framer-cb3dtg { flex: none; width: 100%; }",
	".framer-S5xC9.framer-v-1o9e6lw .framer-2fbv7s { flex-direction: column; gap: 8px; height: min-content; }",
	".framer-S5xC9.framer-v-1o9e6lw .framer-1lm36gk { flex: none; height: min-content; justify-content: center; width: 100%; }",
	...css,
	...css2,
	...css4,
	...css3,
];
var FramerFF7dljYBM = withCSS2(Component2, css6, "framer-S5xC9");
var stdin_default2 = FramerFF7dljYBM;
FramerFF7dljYBM.displayName = "footer";
FramerFF7dljYBM.defaultProps = {
	height: 100,
	width: 1200,
};
addPropertyControls2(FramerFF7dljYBM, {
	variant: {
		options: ["jrG4uFPXX", "rm3kfWLuK"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramerFF7dljYBM,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...SocialFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "rm3kfWLuK",
	xl: "jrG4uFPXX",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var footer_default = ComponentWithRoot;
export { footer_default as default };
