// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7b947833d2a6e6bc "nitro (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Icon } from "./chunks/chunk-WQJQY4NG.js";
import "./chunks/chunk-HR56UER2.js";
import { routes } from "./chunks/chunk-UZPGWJTJ.js";

// virtual:framer-cta
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/Ak229Sivuqgks3BSbrgw/HU4xO2tcvGfUKZblaX6r/hWch4kgQQ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PhosphorFonts = getFonts(Icon);
var serializationHash = "framer-abL8A";
var variantClassNames = {
	ZtT6PJCW5: "framer-v-1fnzntv",
};
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "ZtT6PJCW5",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={
							"https://stfn.lemonsqueezy.com/checkout/buy/32fecd8c-5229-4f30-90cf-3e7f351b502b"
						}
						motionChild={true}
						nodeId={"ZtT6PJCW5"}
						openInNewTab={true}
						scopeId={"hWch4kgQQ"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1fnzntv", className, classNames)} framer-1ullic2`}
							data-framer-name={"Variant 1"}
							layoutDependency={layoutDependency}
							layoutId={"ZtT6PJCW5"}
							ref={refBinding}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
								borderBottomLeftRadius: 11,
								borderBottomRightRadius: 11,
								borderTopLeftRadius: 11,
								borderTopRightRadius: 11,
								boxShadow:
									"0px 0.48174984141951427px 1.252549587690737px -1.25px rgba(0, 0, 0, 0.29), 0px 1.8308266425947657px 4.760149270746391px -2.5px rgba(0, 0, 0, 0.25), 0px 8px 20.8px -3.75px rgba(0, 0, 0, 0.1)",
								...style,
							}}
						>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-8b7mhp-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"HOubIIAq4-container"}
									nodeId={"HOubIIAq4"}
									rendersWithMotion={true}
									scopeId={"hWch4kgQQ"}
								>
									<Icon
										color={"rgb(38, 38, 38)"}
										height={"100%"}
										iconSearch={"House"}
										iconSelection={"Lightning"}
										id={"HOubIIAq4"}
										layoutId={"HOubIIAq4"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										weight={"fill"}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1tvolip"}
								fonts={["GF;Inter-700"]}
								layoutDependency={layoutDependency}
								layoutId={"T_DXRkEAJ"}
								style={{
									"--extracted-r6o4lv": "rgb(35, 31, 32)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7SW50ZXItNzAw",
											"--framer-font-family":
												'"Inter", "Inter Placeholder", sans-serif',
											"--framer-font-size": "13px",
											"--framer-font-weight": "700",
											"--framer-letter-spacing": "-0.4px",
											"--framer-line-height": "1.75em",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(35, 31, 32))",
										}}
									>
										{"Get template \u2014 $39"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-abL8A.framer-1ullic2, .framer-abL8A .framer-1ullic2 { display: block; }",
	".framer-abL8A.framer-1fnzntv { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 7px; height: min-content; justify-content: center; overflow: hidden; padding: 8px 14px 8px 12px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-abL8A .framer-8b7mhp-container { flex: none; height: 18px; position: relative; width: 18px; }",
	".framer-abL8A .framer-1tvolip { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
];
var FramerhWch4kgQQ = withCSS(Component, css, "framer-abL8A");
var stdin_default = FramerhWch4kgQQ;
FramerhWch4kgQQ.displayName = "Framer CTA";
FramerhWch4kgQQ.defaultProps = {
	height: 39,
	width: 170,
};
addFonts(
	FramerhWch4kgQQ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "google",
					style: "normal",
					uiFamilyName: "Inter",
					url: "https://fonts.gstatic.com/s/inter/v20/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuFuYMZ1rib2Bg-4.woff2",
					weight: "700",
				},
			],
		},
		...PhosphorFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:framer-cta
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FramerCtaFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var framer_cta_default = ComponentWithRoot;
export { framer_cta_default as default };
