// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7b947833d2a6e6bc "nitro (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'desktop' | 'laptop' | 'tablet' | 'mobile' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-UZPGWJTJ.js";

// virtual:grid
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/gsNKD66t8HDuFT7UrmuW/UOPWzj7SfgyhcJtt1gWU/ySSziyxBt.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion } from "unframer";
import * as React from "react";
var cycleOrder = ["kjTTbJXGE", "BlMAPpxXV", "JjwQLqDjF", "BELB1AouC"];
var variantClassNames = {
	BELB1AouC: "framer-v-1c37ytq",
	BlMAPpxXV: "framer-v-g83syy",
	JjwQLqDjF: "framer-v-avuh0c",
	kjTTbJXGE: "framer-v-1ndd9z2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var humanReadableVariantMap = {
	desktop: "kjTTbJXGE",
	laptop: "BlMAPpxXV",
	mobile: "BELB1AouC",
	tablet: "JjwQLqDjF",
};
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		duration: 0.3,
		ease: [0.44, 0, 0.56, 1],
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Component = /* @__PURE__ */ React.forwardRef(function (
	{
		id,
		style,
		className,
		width,
		height,
		layoutId,
		variant: outerVariant = "kjTTbJXGE",
		...restProps
	},
	ref,
) {
	const outerVariantId = humanReadableVariantMap[outerVariant];
	const variant = outerVariantId || outerVariant;
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "kjTTbJXGE",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = variants.join("-") + restProps.layoutDependency;
	const isDisplayed = () => {
		if (baseVariant === "BELB1AouC") return false;
		return true;
	};
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx("framer-3NHyP", classNames)}
				style={{
					display: "contents",
				}}
			>
				<motion.div
					{...restProps}
					className={cx("framer-1ndd9z2", className)}
					data-framer-name={"desktop"}
					layoutDependency={layoutDependency}
					layoutId={"kjTTbJXGE"}
					ref={ref}
					style={{
						...style,
					}}
					transition={transition}
					{...addPropertyOverrides(
						{
							BELB1AouC: {
								"data-framer-name": "mobile",
							},
							BlMAPpxXV: {
								"data-framer-name": "laptop",
							},
							JjwQLqDjF: {
								"data-framer-name": "tablet",
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					{isDisplayed() && (
						<motion.div
							className={"framer-1dzatqy"}
							layoutDependency={layoutDependency}
							layoutId={"ZrvOsyRXP"}
							style={{
								background:
									'linear-gradient(180deg, var(--token-90a64261-b816-47fc-8b95-db312dae9b11, rgba(255, 255, 255, 0)) /* {"name":"white 0"} */ 0%, var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25)) /* {"name":"white 25"} */ 100%)',
							}}
							transition={transition}
						/>
					)}
					{isDisplayed() && (
						<motion.div
							className={"framer-1ccifjf"}
							layoutDependency={layoutDependency}
							layoutId={"bVHUJyLex"}
							style={{
								background:
									'linear-gradient(180deg, var(--token-90a64261-b816-47fc-8b95-db312dae9b11, rgba(255, 255, 255, 0)) /* {"name":"white 0"} */ 0%, var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25)) /* {"name":"white 25"} */ 100%)',
							}}
							transition={transition}
						/>
					)}
					{isDisplayed() && (
						<motion.div
							className={"framer-146y3lq"}
							layoutDependency={layoutDependency}
							layoutId={"F3PsHU_px"}
							style={{
								background:
									'linear-gradient(180deg, var(--token-90a64261-b816-47fc-8b95-db312dae9b11, rgba(255, 255, 255, 0)) /* {"name":"white 0"} */ 0%, var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25)) /* {"name":"white 25"} */ 100%)',
							}}
							transition={transition}
						/>
					)}
					{isDisplayed() && (
						<motion.div
							className={"framer-hwpzcs"}
							layoutDependency={layoutDependency}
							layoutId={"vmBNgl1oE"}
							style={{
								background:
									'linear-gradient(180deg, var(--token-90a64261-b816-47fc-8b95-db312dae9b11, rgba(255, 255, 255, 0)) /* {"name":"white 0"} */ 0%, var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25)) /* {"name":"white 25"} */ 100%)',
							}}
							transition={transition}
						/>
					)}
					<motion.div
						className={"framer-1l0vz4l"}
						layoutDependency={layoutDependency}
						layoutId={"IBZzc0xeO"}
						style={{
							background:
								'linear-gradient(180deg, var(--token-90a64261-b816-47fc-8b95-db312dae9b11, rgba(255, 255, 255, 0)) /* {"name":"white 0"} */ 0%, var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25)) /* {"name":"white 25"} */ 100%)',
						}}
						transition={transition}
					/>
					<motion.div
						className={"framer-j8su2i"}
						layoutDependency={layoutDependency}
						layoutId={"pgwa7NSk_"}
						style={{
							background:
								'linear-gradient(180deg, var(--token-90a64261-b816-47fc-8b95-db312dae9b11, rgba(255, 255, 255, 0)) /* {"name":"white 0"} */ 0%, var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25)) /* {"name":"white 25"} */ 100%)',
						}}
						transition={transition}
					/>
					<motion.div
						className={"framer-17yh7lh"}
						layoutDependency={layoutDependency}
						layoutId={"VGLZbUDsF"}
						style={{
							background:
								'linear-gradient(180deg, var(--token-90a64261-b816-47fc-8b95-db312dae9b11, rgba(255, 255, 255, 0)) /* {"name":"white 0"} */ 0%, var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25)) /* {"name":"white 25"} */ 100%)',
						}}
						transition={transition}
					/>
					<motion.div
						className={"framer-1423m7t"}
						layoutDependency={layoutDependency}
						layoutId={"QWmvYU03x"}
						style={{
							background:
								'linear-gradient(180deg, var(--token-90a64261-b816-47fc-8b95-db312dae9b11, rgba(255, 255, 255, 0)) /* {"name":"white 0"} */ 0%, var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25)) /* {"name":"white 25"} */ 100%)',
						}}
						transition={transition}
					/>
					<motion.div
						className={"framer-92rj9z"}
						layoutDependency={layoutDependency}
						layoutId={"kwAWyl_CS"}
						style={{
							background:
								'linear-gradient(180deg, var(--token-90a64261-b816-47fc-8b95-db312dae9b11, rgba(255, 255, 255, 0)) /* {"name":"white 0"} */ 0%, var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25)) /* {"name":"white 25"} */ 100%)',
						}}
						transition={transition}
					/>
				</motion.div>
			</motion.div>
		</LayoutGroup>
	);
});
var css = [
	'.framer-3NHyP [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-3NHyP .framer-ydjy8h { display: block; }",
	".framer-3NHyP .framer-1ndd9z2 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; height: 800px; justify-content: space-between; overflow: hidden; padding: 0px 120px 0px 120px; position: relative; width: 1440px; }",
	".framer-3NHyP .framer-1dzatqy, .framer-3NHyP .framer-1ccifjf, .framer-3NHyP .framer-146y3lq, .framer-3NHyP .framer-hwpzcs, .framer-3NHyP .framer-1l0vz4l, .framer-3NHyP .framer-j8su2i, .framer-3NHyP .framer-17yh7lh, .framer-3NHyP .framer-1423m7t, .framer-3NHyP .framer-92rj9z { flex: none; height: 100%; overflow: hidden; position: relative; width: 1px; z-index: 1; }",
	".framer-3NHyP.framer-v-g83syy .framer-1ndd9z2 { padding: 0px 80px 0px 80px; }",
	".framer-3NHyP.framer-v-avuh0c .framer-1ndd9z2 { padding: 0px 48px 0px 48px; }",
	".framer-3NHyP.framer-v-1c37ytq .framer-1ndd9z2 { padding: 0px 24px 0px 24px; }",
];
var FramerySSziyxBt = withCSS(Component, css, "framer-3NHyP");
var stdin_default = FramerySSziyxBt;
FramerySSziyxBt.displayName = "grid";
FramerySSziyxBt.defaultProps = {
	height: 800,
	width: 1440,
};
addPropertyControls(FramerySSziyxBt, {
	variant: {
		options: ["kjTTbJXGE", "BlMAPpxXV", "JjwQLqDjF", "BELB1AouC"],
		optionTitles: ["desktop", "laptop", "tablet", "mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(FramerySSziyxBt, []);

// virtual:grid
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "BELB1AouC",
	md: "JjwQLqDjF",
	lg: "BlMAPpxXV",
	xl: "kjTTbJXGE",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders GridFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var grid_default = ComponentWithRoot;
export { grid_default as default };
