// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7b947833d2a6e6bc "nitro (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * heading?: string // Heading
 * word1?: string // Word 1
 * word2?: string // Word 2
 * word3?: string // Word 3
 * word4?: string // Word 4
 * word5?: string // Word 5
 * intervalS?: number // Interval S
 * animationS?: number // Animation S
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-XR7KURMW.js";
import { routes } from "./chunks/chunk-UZPGWJTJ.js";

// virtual:heading-cycler
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/9mmrxeh3a8UbgqUtvqbH/RxR8u6CVeFLBtLEfNhS1/YXTexy5H6.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/MlSZUFlnmSucMO0B91dg/3yt9vLfFXGt8LCHf0g1j/WordCycler.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import { useState, useEffect, useRef, useId } from "react";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
var mountedIds = /* @__PURE__ */ new Set();
function WordCycler(props) {
	const {
		word1 = "innovative",
		word2 = "creative",
		word3 = "powerful",
		word4 = "",
		word5 = "",
		color1 = "",
		color2 = "",
		color3 = "",
		color4 = "",
		color5 = "",
		interval = 2,
		animationDuration = 0.3,
	} = props;
	const instanceId = useId();
	const containerRef = useRef(null);
	const [h1ClassName, setH1ClassName] = useState("");
	const [dimensions, setDimensions] = useState({
		width: "auto",
		height: "1em",
	});
	const [displayedIndex, setDisplayedIndex] = useState(0);
	const [isAnimating, setIsAnimating] = useState(false);
	const allWords = [word1, word2, word3, word4, word5];
	const allColors = [color1, color2, color3, color4, color5];
	const filteredIndices = allWords.reduce((acc, w, i) => {
		if (w && w.trim() !== "") acc.push(i);
		return acc;
	}, []);
	const words = filteredIndices.map(i => allWords[i]);
	const colors = filteredIndices.map(i => allColors[i]);
	useEffect(() => {
		mountedIds.clear();
		mountedIds.add(instanceId);
		const measureWithClasses = () => {
			const container = containerRef.current;
			if (!container) return;
			const section =
				container.closest("section") ||
				container.closest("[data-framer-name]")?.parentElement;
			const h1El =
				section?.querySelector('[data-framer-name="H1"] h1') ||
				document.querySelector('[data-framer-name="H1"] h1');
			if (h1El && words.length > 0) {
				setH1ClassName(h1El.className);
				const measurer = document.createElement("span");
				measurer.className = h1El.className;
				measurer.style.position = "absolute";
				measurer.style.visibility = "hidden";
				measurer.style.width = `${container.offsetWidth}px`;
				container.parentElement?.appendChild(measurer);
				let maxHeight = 0;
				words.forEach((word) => {
					measurer.textContent = word;
					maxHeight = Math.max(maxHeight, measurer.offsetHeight);
				});
				measurer.remove();
				setDimensions({
					width: "100%",
					height: `${maxHeight}px`,
				});
			}
		};
		measureWithClasses();
		const resizeObserver = new ResizeObserver(measureWithClasses);
		if (containerRef.current?.parentElement) {
			resizeObserver.observe(containerRef.current.parentElement);
		}
		__unframerWindow.addEventListener("resize", measureWithClasses);
		return () => {
			mountedIds.delete(instanceId);
			__unframerWindow.removeEventListener("resize", measureWithClasses);
			resizeObserver.disconnect();
		};
	}, [instanceId, words.join(",")]);
	useEffect(() => {
		if (RenderTarget.current() === RenderTarget.canvas) return;
		if (words.length <= 1) return;
		if (!mountedIds.has(instanceId)) return;
		const timer = setInterval(() => {
			if (!mountedIds.has(instanceId)) return;
			if (isAnimating) return;
			setIsAnimating(true);
			setTimeout(() => {
				setDisplayedIndex((prev) => (prev + 1) % words.length);
				setIsAnimating(false);
			}, animationDuration * 1e3);
		}, interval * 1e3);
		return () => clearInterval(timer);
	}, [words.length, interval, animationDuration, instanceId, isAnimating]);
	if (words.length === 0) return null;
	const easing = "cubic-bezier(0.44, 0, 0.56, 1)";
	const transition = isAnimating
		? `transform ${animationDuration}s ${easing}, opacity ${animationDuration}s ${easing}`
		: "none";
	const currentWord = words[displayedIndex];
	const nextWord = words[(displayedIndex + 1) % words.length];
	const currentColor = colors[displayedIndex] || undefined;
	const nextColor = colors[(displayedIndex + 1) % words.length] || undefined;
	if (words.length === 1) {
		return (
			<span ref={containerRef} className={h1ClassName} style={currentColor ? { color: currentColor } : undefined}>
				{currentWord}
			</span>
		);
	}
	return (
		<span
			ref={containerRef}
			style={{
				position: "relative",
				width: dimensions.width,
				height: dimensions.height,
				overflow: "hidden",
				display: "inline-block",
				verticalAlign: "bottom",
			}}
		>
			<span
				className={h1ClassName}
				style={{
					position: "absolute",
					left: 0,
					top: 0,
					transform: isAnimating ? "translateY(-100%)" : "translateY(0)",
					opacity: isAnimating ? 0 : 1,
					transition,
					...(currentColor ? { color: currentColor } : {}),
				}}
			>
				{currentWord}
			</span>
			<span
				className={h1ClassName}
				style={{
					position: "absolute",
					left: 0,
					top: 0,
					transform: isAnimating ? "translateY(0)" : "translateY(100%)",
					opacity: isAnimating ? 1 : 0,
					transition,
					...(nextColor ? { color: nextColor } : {}),
				}}
			>
				{nextWord}
			</span>
		</span>
	);
}
addPropertyControls(WordCycler, {
	word1: {
		type: ControlType.String,
		title: "Word 1",
		defaultValue: "innovative",
	},
	word2: {
		type: ControlType.String,
		title: "Word 2",
		defaultValue: "creative",
	},
	word3: {
		type: ControlType.String,
		title: "Word 3",
		defaultValue: "powerful",
	},
	word4: {
		type: ControlType.String,
		title: "Word 4",
		defaultValue: "",
	},
	word5: {
		type: ControlType.String,
		title: "Word 5",
		defaultValue: "",
	},
	interval: {
		type: ControlType.Number,
		title: "Interval (s)",
		defaultValue: 2,
		min: 0.5,
		max: 10,
		step: 0.1,
	},
	animationDuration: {
		type: ControlType.Number,
		title: "Animation (s)",
		defaultValue: 0.3,
		min: 0.1,
		max: 1,
		step: 0.05,
	},
});

// /:https://framerusercontent.com/modules/9mmrxeh3a8UbgqUtvqbH/RxR8u6CVeFLBtLEfNhS1/YXTexy5H6.js
var WordCyclerFonts = getFonts(WordCycler);
var serializationHash = "framer-UGC8y";
var variantClassNames = {
	qKTmIRzma: "framer-v-1kiwgi8",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	animationS,
	heading,
	height,
	id,
	intervalS,
	width,
	word1,
	word2,
	word3,
	word4,
	word5,
	color1,
	color2,
	color3,
	color4,
	color5,
	...props
}) => {
	return {
		...props,
		C1iMkXo89: word4 ?? props.C1iMkXo89,
		DvYyl8ACl: word2 ?? props.DvYyl8ACl ?? "software interfaces",
		F5ik83oFx: word3 ?? props.F5ik83oFx ?? "interactive experiences",
		IXjNbbM7p: animationS ?? props.IXjNbbM7p ?? 0.3,
		kKjkRWIuM:
			heading ?? props.kKjkRWIuM ?? "a product design partner with focus on",
		m3wlapqCe: intervalS ?? props.m3wlapqCe ?? 2,
		pCl4EXN39: word1 ?? props.pCl4EXN39 ?? "no-code websites",
		Y0F41o9li: word5 ?? props.Y0F41o9li,
		_color1: color1 ?? props._color1 ?? "",
		_color2: color2 ?? props._color2 ?? "",
		_color3: color3 ?? props._color3 ?? "",
		_color4: color4 ?? props._color4 ?? "",
		_color5: color5 ?? props._color5 ?? "",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		kKjkRWIuM: kKjkRWIuM2,
		pCl4EXN39: pCl4EXN392,
		DvYyl8ACl: DvYyl8ACl2,
		F5ik83oFx: F5ik83oFx2,
		C1iMkXo89: C1iMkXo892,
		Y0F41o9li: Y0F41o9li2,
		m3wlapqCe: m3wlapqCe2,
		IXjNbbM7p: IXjNbbM7p2,
		_color1,
		_color2,
		_color3,
		_color4,
		_color5,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "qKTmIRzma",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1kiwgi8",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"qKTmIRzma"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1bzkj92"}
							data-framer-name={"H1"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"Wlwy2nTJT"}
							style={{
								"--extracted-gdpscs":
									"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={kKjkRWIuM2}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h1
									className={"framer-styles-preset-3nqyhf"}
									data-styles-preset={"YAP816Y5n"}
									style={{
										"--framer-text-alignment": "left",
										"--framer-text-color":
											"var(--extracted-gdpscs, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
									}}
								>
									{"a product design partner with focus on"}
								</motion.h1>
							</React.Fragment>
						</RichText>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-7rrps3-container"}
								isAuthoredByUser={true}
								layoutDependency={layoutDependency}
								layoutId={"cVpDR9ige-container"}
								nodeId={"cVpDR9ige"}
								rendersWithMotion={true}
								scopeId={"YXTexy5H6"}
							>
							<WordCycler
								animationDuration={IXjNbbM7p2}
								height={"100%"}
								id={"cVpDR9ige"}
								interval={m3wlapqCe2}
								layoutId={"cVpDR9ige"}
								style={{
									width: "100%",
								}}
								width={"100%"}
								word1={pCl4EXN392}
								word2={DvYyl8ACl2}
								word3={F5ik83oFx2}
								word4={C1iMkXo892}
								word5={Y0F41o9li2}
								color1={_color1}
								color2={_color2}
								color3={_color3}
								color4={_color4}
								color5={_color5}
							/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-UGC8y.framer-3f8m0k, .framer-UGC8y .framer-3f8m0k { display: block; }",
	".framer-UGC8y.framer-1kiwgi8 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1200px; }",
	".framer-UGC8y .framer-1bzkj92 { --framer-text-wrap-override: balance; flex: none; height: auto; max-width: 1200px; position: relative; width: 100%; z-index: 1; }",
	".framer-UGC8y .framer-7rrps3-container { flex: none; height: auto; position: relative; width: 100%; }",
	...css,
];
var FramerYXTexy5H6 = withCSS(Component, css2, "framer-UGC8y");
var stdin_default = FramerYXTexy5H6;
FramerYXTexy5H6.displayName = "Heading Cycler";
FramerYXTexy5H6.defaultProps = {
	height: 390,
	width: 1200,
};
addPropertyControls2(FramerYXTexy5H6, {
	kKjkRWIuM: {
		defaultValue: "a product design partner with focus on",
		displayTextArea: false,
		title: "Heading",
		type: ControlType2.String,
	},
	pCl4EXN39: {
		defaultValue: "no-code websites",
		title: "Word 1",
		type: ControlType2.String,
	},
	DvYyl8ACl: {
		defaultValue: "software interfaces",
		title: "Word 2",
		type: ControlType2.String,
	},
	F5ik83oFx: {
		defaultValue: "interactive experiences",
		title: "Word 3",
		type: ControlType2.String,
	},
	C1iMkXo89: {
		defaultValue: "",
		title: "Word 4",
		type: ControlType2.String,
	},
	Y0F41o9li: {
		defaultValue: "",
		title: "Word 5",
		type: ControlType2.String,
	},
	m3wlapqCe: {
		defaultValue: 2,
		max: 10,
		min: 0.5,
		step: 0.1,
		title: "Interval S",
		type: ControlType2.Number,
	},
	IXjNbbM7p: {
		defaultValue: 0.3,
		max: 1,
		min: 0.1,
		step: 0.05,
		title: "Animation S",
		type: ControlType2.Number,
	},
});
addFonts(
	FramerYXTexy5H6,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...WordCyclerFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:heading-cycler
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeadingCyclerFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var heading_cycler_default = ComponentWithRoot;
export { heading_cycler_default as default };
