// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7b947833d2a6e6bc "nitro (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'desktop' | 'mobile' | 'mobile expanded' // Variant
}} Props

 */
import {
	className as className3,
	className2 as className4,
	css as css3,
	css2 as css4,
	fonts as fonts3,
	fonts2 as fonts4,
} from "./chunks/chunk-67WPTMYE.js";
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-7JGR5MG2.js";
import {
	className as className6,
	css as css6,
	fonts as fonts6,
} from "./chunks/chunk-KQJZ5C44.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-FCJZKTDO.js";
import { className, css, fonts } from "./chunks/chunk-G6UXAXIU.js";
import { routes } from "./chunks/chunk-UZPGWJTJ.js";

// virtual:nav-links
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/qRcjzv8NtKz5wWuO7PNZ/XL4ZBSGmha8tubyRi7Z5/l9GPG8fUR.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["fZfZdYOHc", "FKbEZPJLt", "nmeT8pYVr"];
var serializationHash = "framer-Dpiib";
var variantClassNames = {
	FKbEZPJLt: "framer-v-1g5cch4",
	fZfZdYOHc: "framer-v-1kgt43p",
	nmeT8pYVr: "framer-v-odr3x6",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"mobile expanded": "nmeT8pYVr",
	desktop: "fZfZdYOHc",
	mobile: "FKbEZPJLt",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "fZfZdYOHc",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className7,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "fZfZdYOHc",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1blu102 = activeVariantCallback(async (...args) => {
		setVariant("nmeT8pYVr");
	});
	const onTapukg73f = activeVariantCallback(async (...args) => {
		setVariant("FKbEZPJLt");
	});
	const sharedStyleClassNames = [
		className2,
		className3,
		className6,
		className5,
		className,
		className4,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["FKbEZPJLt", "nmeT8pYVr"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "FKbEZPJLt") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1kgt43p",
							className7,
							classNames,
						)}
						data-framer-name={"desktop"}
						layoutDependency={layoutDependency}
						layoutId={"fZfZdYOHc"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								FKbEZPJLt: {
									"data-framer-name": "mobile",
								},
								nmeT8pYVr: {
									"data-framer-name": "mobile expanded",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1ukyk27"}
							layoutDependency={layoutDependency}
							layoutId={"dOzdvxJZC"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1199g8r"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"y3MlodPt8"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-ugcj2n"}
										data-styles-preset={"JLUy8CuLJ"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
										}}
									>
										<Link
											href={{
												webPageId: "augiA20Il",
											}}
											motionChild={true}
											nodeId={"y3MlodPt8"}
											openInNewTab={false}
											relValues={[]}
											scopeId={"l9GPG8fUR"}
											smoothScroll={false}
										>
											<motion.a
												className={"framer-styles-preset-1wicq5s"}
												data-styles-preset={"ro7OPezbn"}
											>
												{".nitro"}
											</motion.a>
										</Link>
									</motion.p>
								</React.Fragment>
							</RichText>
							{isDisplayed() && (
								<motion.div
									className={"framer-ic0eg3"}
									layoutDependency={layoutDependency}
									layoutId={"DjZ2Gw0jy"}
									{...addPropertyOverrides(
										{
											FKbEZPJLt: {
												"data-highlight": true,
												onTap: onTap1blu102,
											},
											nmeT8pYVr: {
												"data-highlight": true,
												onTap: onTapukg73f,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-19sbi7g"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"ujoIeF3gL"}
										style={{
											"--extracted-a0htzi":
												"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										variants={{
											nmeT8pYVr: {
												"--extracted-a0htzi":
													"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
											},
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												nmeT8pYVr: {
													children: (
														<React.Fragment>
															<motion.h3
																className={"framer-styles-preset-12lj5ox"}
																data-styles-preset={"YckFIlg3V"}
																style={{
																	"--framer-text-alignment": "right",
																	"--framer-text-color":
																		"var(--extracted-a0htzi, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
																}}
															>
																{"close"}
															</motion.h3>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.h3
												className={"framer-styles-preset-12lj5ox"}
												data-styles-preset={"YckFIlg3V"}
												style={{
													"--framer-text-alignment": "right",
													"--framer-text-color":
														"var(--extracted-a0htzi, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
												}}
											>
												{"menu"}
											</motion.h3>
										</React.Fragment>
									</RichText>
									<motion.div
										className={"framer-n6141n"}
										layoutDependency={layoutDependency}
										layoutId={"ixsCz6LjD"}
									>
										<motion.div
											className={"framer-lvxq0l"}
											layoutDependency={layoutDependency}
											layoutId={"cwTUeo58N"}
											style={{
												backgroundColor:
													"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
												rotate: 0,
											}}
											variants={{
												nmeT8pYVr: {
													backgroundColor:
														"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
													rotate: 45,
												},
											}}
										/>
										<motion.div
											className={"framer-1mzzdtr"}
											layoutDependency={layoutDependency}
											layoutId={"RgEOaqqGl"}
											style={{
												backgroundColor:
													"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
												rotate: 0,
											}}
											variants={{
												nmeT8pYVr: {
													backgroundColor:
														"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
													rotate: -45,
												},
											}}
										/>
									</motion.div>
								</motion.div>
							)}
						</motion.div>
						{isDisplayed1() && (
							<motion.div
								className={"framer-1vrsr0a"}
								layoutDependency={layoutDependency}
								layoutId={"nyQortf8I"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-ev2odk"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"dVkQvmotB"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
									}}
									variants={{
										nmeT8pYVr: {
											"--extracted-1of0zx5":
												"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											nmeT8pYVr: {
												children: (
													<React.Fragment>
														<motion.h2
															className={"framer-styles-preset-1wml6uu"}
															data-styles-preset={"fVxnimdqP"}
															style={{
																"--framer-text-alignment": "right",
																"--framer-text-color":
																	"var(--extracted-1of0zx5, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
															}}
														>
															<Link
																href={{
																	webPageId: "xaVhC_xTq",
																}}
																motionChild={true}
																nodeId={"dVkQvmotB"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"l9GPG8fUR"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wicq5s"}
																	data-styles-preset={"ro7OPezbn"}
																>
																	{"projects"}
																</motion.a>
															</Link>
														</motion.h2>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-21ogod"}
											data-styles-preset={"xZndidUCt"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
											}}
										>
											<Link
												href={{
													webPageId: "xaVhC_xTq",
												}}
												motionChild={true}
												nodeId={"dVkQvmotB"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"l9GPG8fUR"}
												smoothScroll={false}
											>
												<motion.a
													className={"framer-styles-preset-1wicq5s"}
													data-styles-preset={"ro7OPezbn"}
												>
													{"projects"}
												</motion.a>
											</Link>
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1d11t8k"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"XSjRqx7kD"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
									}}
									variants={{
										nmeT8pYVr: {
											"--extracted-1of0zx5":
												"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											nmeT8pYVr: {
												children: (
													<React.Fragment>
														<motion.h2
															className={"framer-styles-preset-1wml6uu"}
															data-styles-preset={"fVxnimdqP"}
															style={{
																"--framer-text-alignment": "right",
																"--framer-text-color":
																	"var(--extracted-1of0zx5, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
															}}
														>
															<Link
																href={{
																	webPageId: "BQxSXX7Vv",
																}}
																motionChild={true}
																nodeId={"XSjRqx7kD"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"l9GPG8fUR"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wicq5s"}
																	data-styles-preset={"ro7OPezbn"}
																>
																	{"about"}
																</motion.a>
															</Link>
														</motion.h2>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-21ogod"}
											data-styles-preset={"xZndidUCt"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
											}}
										>
											<Link
												href={{
													webPageId: "BQxSXX7Vv",
												}}
												motionChild={true}
												nodeId={"XSjRqx7kD"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"l9GPG8fUR"}
												smoothScroll={false}
											>
												<motion.a
													className={"framer-styles-preset-1wicq5s"}
													data-styles-preset={"ro7OPezbn"}
												>
													{"about"}
												</motion.a>
											</Link>
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1p9da4e"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"zxsJjt8xJ"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
									}}
									variants={{
										nmeT8pYVr: {
											"--extracted-1of0zx5":
												"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											nmeT8pYVr: {
												children: (
													<React.Fragment>
														<motion.h2
															className={"framer-styles-preset-1wml6uu"}
															data-styles-preset={"fVxnimdqP"}
															style={{
																"--framer-text-alignment": "right",
																"--framer-text-color":
																	"var(--extracted-1of0zx5, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
															}}
														>
															<Link
																href={{
																	webPageId: "ElzBhd0WH",
																}}
																motionChild={true}
																nodeId={"zxsJjt8xJ"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"l9GPG8fUR"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wicq5s"}
																	data-styles-preset={"ro7OPezbn"}
																>
																	{"notes"}
																</motion.a>
															</Link>
														</motion.h2>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-21ogod"}
											data-styles-preset={"xZndidUCt"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
											}}
										>
											<Link
												href={{
													webPageId: "ElzBhd0WH",
												}}
												motionChild={true}
												nodeId={"zxsJjt8xJ"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"l9GPG8fUR"}
												smoothScroll={false}
											>
												<motion.a
													className={"framer-styles-preset-1wicq5s"}
													data-styles-preset={"ro7OPezbn"}
												>
													{"notes"}
												</motion.a>
											</Link>
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1my19s4"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"lpxXlAvSC"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
									}}
									variants={{
										nmeT8pYVr: {
											"--extracted-1of0zx5":
												"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											nmeT8pYVr: {
												children: (
													<React.Fragment>
														<motion.h2
															className={"framer-styles-preset-1wml6uu"}
															data-styles-preset={"fVxnimdqP"}
															style={{
																"--framer-text-alignment": "right",
																"--framer-text-color":
																	"var(--extracted-1of0zx5, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
															}}
														>
															<Link
																href={{
																	webPageId: "jQl8KobkC",
																}}
																motionChild={true}
																nodeId={"lpxXlAvSC"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"l9GPG8fUR"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1wicq5s"}
																	data-styles-preset={"ro7OPezbn"}
																>
																	{"contact"}
																</motion.a>
															</Link>
														</motion.h2>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-21ogod"}
											data-styles-preset={"xZndidUCt"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
											}}
										>
											<Link
												href={{
													webPageId: "jQl8KobkC",
												}}
												motionChild={true}
												nodeId={"lpxXlAvSC"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"l9GPG8fUR"}
												smoothScroll={false}
											>
												<motion.a
													className={"framer-styles-preset-1wicq5s"}
													data-styles-preset={"ro7OPezbn"}
												>
													{"contact"}
												</motion.a>
											</Link>
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-e4e94c"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"EO0kp1jjT"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-8b7699fe-a6ed-49e3-97cd-679d496bde7f, rgb(0, 255, 119))",
									}}
									variants={{
										nmeT8pYVr: {
											"--extracted-1of0zx5":
												"var(--token-8b7699fe-a6ed-49e3-97cd-679d496bde7f, rgb(0, 255, 119))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											nmeT8pYVr: {
												children: (
													<React.Fragment>
														<motion.h2
															className={"framer-styles-preset-1wml6uu"}
															data-styles-preset={"fVxnimdqP"}
															style={{
																"--framer-text-alignment": "right",
																"--framer-text-color":
																	"var(--extracted-1of0zx5, var(--token-8b7699fe-a6ed-49e3-97cd-679d496bde7f, rgb(0, 255, 119)))",
															}}
														>
															<Link
																href={"https://framer.link/MvMdlCP"}
																motionChild={true}
																nodeId={"EO0kp1jjT"}
																openInNewTab={true}
																relValues={[]}
																scopeId={"l9GPG8fUR"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-6hy7sq"}
																	data-styles-preset={"xSmbUc6JM"}
																>
																	{"get template"}
																</motion.a>
															</Link>
														</motion.h2>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-21ogod"}
											data-styles-preset={"xZndidUCt"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-8b7699fe-a6ed-49e3-97cd-679d496bde7f, rgb(0, 255, 119)))",
											}}
										>
											<Link
												href={"https://framer.link/MvMdlCP"}
												motionChild={true}
												nodeId={"EO0kp1jjT"}
												openInNewTab={true}
												relValues={[]}
												scopeId={"l9GPG8fUR"}
												smoothScroll={false}
											>
												<motion.a
													className={"framer-styles-preset-6hy7sq"}
													data-styles-preset={"xSmbUc6JM"}
												>
													{"get template"}
												</motion.a>
											</Link>
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css7 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Dpiib.framer-15by8qu, .framer-Dpiib .framer-15by8qu { display: block; }",
	".framer-Dpiib.framer-1kgt43p { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: center; overflow: hidden; padding: 24px 0px 24px 0px; position: relative; width: 1200px; }",
	".framer-Dpiib .framer-1ukyk27 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-Dpiib .framer-1199g8r, .framer-Dpiib .framer-19sbi7g { flex: none; height: auto; max-width: 1920px; position: relative; white-space: pre-wrap; width: auto; word-break: break-word; word-wrap: break-word; }",
	".framer-Dpiib .framer-ic0eg3 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-Dpiib .framer-n6141n { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 20px); overflow: visible; position: relative; width: 20px; }",
	".framer-Dpiib .framer-lvxq0l { flex: none; height: 2px; overflow: visible; position: absolute; right: 0px; top: 5px; width: 16px; }",
	".framer-Dpiib .framer-1mzzdtr { bottom: 1px; flex: none; height: 2px; overflow: visible; position: absolute; right: 0px; width: 16px; }",
	".framer-Dpiib .framer-1vrsr0a { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-Dpiib .framer-ev2odk, .framer-Dpiib .framer-1d11t8k, .framer-Dpiib .framer-1p9da4e, .framer-Dpiib .framer-1my19s4, .framer-Dpiib .framer-e4e94c { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-Dpiib.framer-v-1g5cch4.framer-1kgt43p { padding: 16px 0px 16px 0px; }",
	".framer-Dpiib.framer-v-1g5cch4 .framer-1ukyk27 { gap: unset; justify-content: space-between; }",
	".framer-Dpiib.framer-v-1g5cch4 .framer-ic0eg3, .framer-Dpiib.framer-v-odr3x6 .framer-ic0eg3 { cursor: pointer; flex: none; width: min-content; }",
	".framer-Dpiib.framer-v-1g5cch4 .framer-19sbi7g, .framer-Dpiib.framer-v-odr3x6 .framer-19sbi7g { max-width: unset; white-space: pre; }",
	".framer-Dpiib.framer-v-odr3x6.framer-1kgt43p { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 80px; justify-content: flex-start; min-height: calc(var(--framer-viewport-height, 100vh) * 1); padding: 16px 0px 16px 0px; }",
	".framer-Dpiib.framer-v-odr3x6 .framer-1ukyk27 { flex: none; gap: unset; justify-content: space-between; width: 100%; }",
	".framer-Dpiib.framer-v-odr3x6 .framer-lvxq0l { bottom: 6px; top: unset; }",
	".framer-Dpiib.framer-v-odr3x6 .framer-1mzzdtr { bottom: 6px; }",
	".framer-Dpiib.framer-v-odr3x6 .framer-1vrsr0a { flex-direction: column; gap: 36px; width: 100%; }",
	".framer-Dpiib.framer-v-odr3x6 .framer-ev2odk, .framer-Dpiib.framer-v-odr3x6 .framer-1d11t8k, .framer-Dpiib.framer-v-odr3x6 .framer-1p9da4e, .framer-Dpiib.framer-v-odr3x6 .framer-1my19s4, .framer-Dpiib.framer-v-odr3x6 .framer-e4e94c { white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css2,
	...css3,
	...css6,
	...css5,
	...css,
	...css4,
];
var Framerl9GPG8fUR = withCSS(Component, css7, "framer-Dpiib");
var stdin_default = Framerl9GPG8fUR;
Framerl9GPG8fUR.displayName = "nav links";
Framerl9GPG8fUR.defaultProps = {
	height: 83,
	width: 1200,
};
addPropertyControls(Framerl9GPG8fUR, {
	variant: {
		options: ["fZfZdYOHc", "FKbEZPJLt", "nmeT8pYVr"],
		optionTitles: ["desktop", "mobile", "mobile expanded"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerl9GPG8fUR,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts6),
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts4),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:nav-links
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "FKbEZPJLt",
	xl: "fZfZdYOHc",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavLinksFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var nav_links_default = ComponentWithRoot;
export { nav_links_default as default };
