// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7b947833d2a6e6bc "nitro (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-7JGR5MG2.js";
import { Grain } from "./chunks/chunk-J6FBOBB4.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-KQJZ5C44.js";
import { stdin_default } from "./chunks/chunk-2FJHF24R.js";
import { className, css, fonts } from "./chunks/chunk-EGECXSOW.js";
import { routes } from "./chunks/chunk-UZPGWJTJ.js";

// virtual:post
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/lc0f6ddnqpFwilbcpD3p/j4dvxFSkPBgMoGiqmt52/VMnGi0NIs.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleCode,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var GrainFonts = getFonts(Grain);
var AimFonts = getFonts(stdin_default);
var enabledGestures = {
	ax1zjzShX: {
		hover: true,
	},
	H1zMAcI_H: {
		hover: true,
	},
};
var cycleOrder = ["H1zMAcI_H", "ax1zjzShX", "Pt4KWfrzS"];
var serializationHash = "framer-aPRfe";
var variantClassNames = {
	ax1zjzShX: "framer-v-ecvvo7",
	H1zMAcI_H: "framer-v-dj3apl",
	Pt4KWfrzS: "framer-v-j97g0p",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var sharedDateFormatter = (value, formatOptions, locale) => {
	if (typeof value !== "string") return "";
	const date = new Date(value);
	if (isNaN(date.getTime())) return "";
	const fallbackLocale = "en-US";
	try {
		return date.toLocaleString(locale || fallbackLocale, formatOptions);
	} catch {
		return date.toLocaleString(fallbackLocale, formatOptions);
	}
};
var dateOptions = {
	dateStyle: "medium",
	timeZone: "UTC",
};
var toDateString = (value, activeLocale) => {
	return sharedDateFormatter(value, dateOptions, activeLocale);
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "H1zMAcI_H",
	"Variant 2": "ax1zjzShX",
	"Variant 3": "Pt4KWfrzS",
};
var getProps = ({ date, height, id, image, link, title, width, ...props }) => {
	return {
		...props,
		AU3sHoeBe: image ?? props.AU3sHoeBe,
		eRPXAioTG: date ?? props.eRPXAioTG ?? "2022-04-08T00:00:00.000Z",
		RYVwbPoS8: title ?? props.RYVwbPoS8 ?? "latest post",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "H1zMAcI_H",
		Z1PV50RCS: link ?? props.Z1PV50RCS,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		AU3sHoeBe,
		eRPXAioTG,
		RYVwbPoS8,
		Z1PV50RCS,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "H1zMAcI_H",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className3, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "Pt4KWfrzS") return false;
		return true;
	};
	const activeLocaleCode = useLocaleCode();
	const textContent = toDateString(eRPXAioTG, activeLocaleCode);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={Z1PV50RCS}
						motionChild={true}
						nodeId={"H1zMAcI_H"}
						scopeId={"VMnGi0NIs"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-dj3apl", className4, classNames)} framer-1qfdnn1`}
							data-framer-name={"Variant 1"}
							layoutDependency={layoutDependency}
							layoutId={"H1zMAcI_H"}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"ax1zjzShX-hover": {
										"data-framer-name": void 0,
									},
									"H1zMAcI_H-hover": {
										"data-framer-name": void 0,
									},
									ax1zjzShX: {
										"data-framer-name": "Variant 2",
									},
									Pt4KWfrzS: {
										"data-framer-name": "Variant 3",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-96x06s"}
								data-framer-name={"Top Content"}
								layoutDependency={layoutDependency}
								layoutId={"FCtxAYc8u"}
							>
								<motion.div
									className={"framer-rdlf2h"}
									data-framer-name={"Image"}
									layoutDependency={layoutDependency}
									layoutId={"L1SY4tNBy"}
									style={{
										backgroundColor:
											"var(--token-cd708a3c-25bb-4606-92f4-351c74f13945, rgb(0, 0, 0))",
									}}
								>
									<Image
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0 + 0 + 0 + -0.5,
											),
											sizes: `max(${componentViewport?.width || "100vw"} * 0.75, 1px)`,
											...toResponsiveImage(AU3sHoeBe),
										}}
										className={"framer-15npj1b"}
										layoutDependency={layoutDependency}
										layoutId={"dXGTXd7mF"}
										style={{
											borderBottomLeftRadius: 2,
											borderBottomRightRadius: 2,
											borderTopLeftRadius: 2,
											borderTopRightRadius: 2,
											filter: "none",
											WebkitFilter: "none",
										}}
										variants={{
											"ax1zjzShX-hover": {
												filter: "grayscale(0)",
												WebkitFilter: "grayscale(0)",
											},
											"H1zMAcI_H-hover": {
												filter: "grayscale(0)",
												WebkitFilter: "grayscale(0)",
											},
										}}
										{...addPropertyOverrides(
											{
												"H1zMAcI_H-hover": {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) + 0 + 0 + 0 + -30.25,
														),
														sizes: `calc(max(${componentViewport?.width || "100vw"} * 0.75, 1px) * 1.1)`,
														...toResponsiveImage(AU3sHoeBe),
													},
												},
												ax1zjzShX: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) + 0 + 0 + 0,
														),
														sizes: `max(max(${componentViewport?.width || "100vw"} / 2, 1px) * 0.75, 1px)`,
														...toResponsiveImage(AU3sHoeBe),
													},
												},
												Pt4KWfrzS: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) + 0 + 0 + 0 + 0,
														),
														sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
														...toResponsiveImage(AU3sHoeBe),
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-bppc2u-container"}
												isAuthoredByUser={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"yTYTHdXjN-container"}
												nodeId={"yTYTHdXjN"}
												rendersWithMotion={true}
												scopeId={"VMnGi0NIs"}
											>
												<Grain
													height={"100%"}
													id={"yTYTHdXjN"}
													layoutId={"yTYTHdXjN"}
													opacity={0.03}
													style={{
														height: "100%",
														width: "100%",
													}}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</Image>
								</motion.div>
								{isDisplayed() && (
									<motion.div
										className={"framer-1gnwlwt"}
										data-framer-name={"Tagline"}
										layoutDependency={layoutDependency}
										layoutId={"AOdacAuGk"}
									>
										<motion.div
											className={"framer-1m5j4xe"}
											layoutDependency={layoutDependency}
											layoutId={"TmQ5dHFLT"}
											style={{
												opacity: 1,
											}}
											variants={{
												"H1zMAcI_H-hover": {
													opacity: 1,
												},
												ax1zjzShX: {
													opacity: 0,
												},
											}}
										>
											<motion.div
												className={"framer-1cjq727"}
												layoutDependency={layoutDependency}
												layoutId={"w0PqbNMQM"}
												style={{
													backgroundColor:
														"var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25))",
												}}
											/>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1yucwke"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"vyscyqMMg"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1i4mbrj"}
														data-styles-preset={"s0y5Rymtd"}
													>
														{"latest post"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
								)}
							</motion.div>
							<motion.div
								className={"framer-83swx4"}
								data-framer-name={"Bottom Content"}
								layoutDependency={layoutDependency}
								layoutId={"aXUuWNuXG"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-je5cxs"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"prN8abM_n"}
									style={{
										"--extracted-a0htzi":
											"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={RYVwbPoS8}
									variants={{
										"ax1zjzShX-hover": {
											"--extracted-a0htzi":
												"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
										},
										"H1zMAcI_H-hover": {
											"--extracted-a0htzi":
												"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"ax1zjzShX-hover": {
												children: (
													<React.Fragment>
														<motion.h3
															className={"framer-styles-preset-12lj5ox"}
															data-styles-preset={"YckFIlg3V"}
															style={{
																"--framer-text-color":
																	"var(--extracted-a0htzi, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
															}}
														>
															{"latest post"}
														</motion.h3>
													</React.Fragment>
												),
											},
											"H1zMAcI_H-hover": {
												children: (
													<React.Fragment>
														<motion.h3
															className={"framer-styles-preset-12lj5ox"}
															data-styles-preset={"YckFIlg3V"}
															style={{
																"--framer-text-color":
																	"var(--extracted-a0htzi, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
															}}
														>
															{"latest post"}
														</motion.h3>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.h3
											className={"framer-styles-preset-12lj5ox"}
											data-styles-preset={"YckFIlg3V"}
											style={{
												"--framer-text-color":
													"var(--extracted-a0htzi, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
											}}
										>
											{"latest post"}
										</motion.h3>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-13iu40s"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Nu88uTUXW"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={textContent}
									variants={{
										"ax1zjzShX-hover": {
											"--extracted-r6o4lv":
												"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
										},
										"H1zMAcI_H-hover": {
											"--extracted-r6o4lv":
												"var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"ax1zjzShX-hover": {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-21ogod"}
															data-styles-preset={"xZndidUCt"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
															}}
														>
															{"Apr 8, 2022"}
														</motion.p>
													</React.Fragment>
												),
											},
											"H1zMAcI_H-hover": {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-21ogod"}
															data-styles-preset={"xZndidUCt"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6b60c4fa-a3b2-4ea3-8e1a-4202c7b68ede, rgba(255, 255, 255, 0.5)))",
															}}
														>
															{"Apr 8, 2022"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-21ogod"}
											data-styles-preset={"xZndidUCt"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25)))",
											}}
										>
											{"Apr 8, 2022"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							{isDisplayed() && (
								<motion.div
									className={"framer-1tmuvin"}
									data-framer-name={"Aim Wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"c7q3NiQJP"}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-la43ty-container"}
											layoutDependency={layoutDependency}
											layoutId={"sS25ivm9T-container"}
											nodeId={"sS25ivm9T"}
											rendersWithMotion={true}
											scopeId={"VMnGi0NIs"}
										>
											{_jsx(stdin_default, {
												height: "100%",
												id: "sS25ivm9T",
												layoutId: "sS25ivm9T",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: "YnXfrsvOD",
												width: "100%",
												...addPropertyOverrides(
													{
														"ax1zjzShX-hover": {
															variant: "gWsTOWKop",
														},
														"H1zMAcI_H-hover": {
															variant: "gWsTOWKop",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							)}
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-aPRfe.framer-1qfdnn1, .framer-aPRfe .framer-1qfdnn1 { display: block; }",
	".framer-aPRfe.framer-dj3apl { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: 711px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 1200px; }",
	".framer-aPRfe .framer-96x06s { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-aPRfe .framer-rdlf2h { flex: 3 0 0px; gap: 10px; height: 595px; overflow: hidden; position: relative; width: 1px; }",
	".framer-aPRfe .framer-15npj1b { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; position: absolute; top: calc(49.91596638655464% - 100% / 2); width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-aPRfe .framer-bppc2u-container { flex: none; height: 100%; left: 0px; position: absolute; top: 0px; width: 100%; }",
	".framer-aPRfe .framer-1gnwlwt { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: sticky; top: 120px; width: 1px; z-index: 1; }",
	".framer-aPRfe .framer-1m5j4xe { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 16px; position: relative; width: 1px; z-index: 1; }",
	".framer-aPRfe .framer-1cjq727 { flex: 1 0 0px; height: 1px; overflow: hidden; position: relative; width: 1px; }",
	".framer-aPRfe .framer-1yucwke { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-aPRfe .framer-83swx4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-aPRfe .framer-je5cxs, .framer-aPRfe .framer-13iu40s { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-aPRfe .framer-1tmuvin { flex: 1 0 0px; height: 1px; overflow: visible; position: relative; width: 100%; }",
	".framer-aPRfe .framer-la43ty-container { bottom: 0px; flex: none; height: 36px; position: absolute; right: 0px; width: 36px; }",
	".framer-aPRfe.framer-v-ecvvo7.framer-dj3apl { flex-direction: row; gap: 0px; height: min-content; }",
	".framer-aPRfe.framer-v-ecvvo7 .framer-96x06s { flex: 4 0 0px; height: 333px; width: 1px; }",
	".framer-aPRfe.framer-v-ecvvo7 .framer-rdlf2h { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; height: 100%; justify-content: center; padding: 0px; }",
	".framer-aPRfe.framer-v-ecvvo7 .framer-15npj1b, .framer-aPRfe.framer-v-j97g0p .framer-15npj1b { left: unset; position: relative; top: unset; }",
	".framer-aPRfe.framer-v-ecvvo7 .framer-83swx4 { flex: 3 0 0px; width: 1px; }",
	".framer-aPRfe.framer-v-ecvvo7 .framer-1tmuvin { align-self: stretch; height: auto; width: 1px; }",
	".framer-aPRfe.framer-v-j97g0p.framer-dj3apl { cursor: unset; height: min-content; width: 608px; }",
	".framer-aPRfe.framer-v-j97g0p .framer-96x06s { justify-content: flex-start; }",
	".framer-aPRfe.framer-v-j97g0p .framer-rdlf2h { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: var(--framer-aspect-ratio-supported, 200px); justify-content: center; padding: 0px; }",
	".framer-aPRfe.framer-v-dj3apl.hover .framer-15npj1b { height: 110%; left: calc(50.00000000000002% - 110.00000000000001% / 2); top: calc(49.91596638655464% - 110.00000000000001% / 2); width: 110%; }",
	".framer-aPRfe.framer-v-dj3apl.hover .framer-bppc2u-container { bottom: 0px; height: unset; right: 0px; width: unset; }",
	".framer-aPRfe.framer-v-ecvvo7.hover .framer-15npj1b { left: unset; top: unset; }",
	...css,
	...css3,
	...css2,
];
var FramerVMnGi0NIs = withCSS(Component, css4, "framer-aPRfe");
var stdin_default2 = FramerVMnGi0NIs;
FramerVMnGi0NIs.displayName = "post";
FramerVMnGi0NIs.defaultProps = {
	height: 711,
	width: 1200,
};
addPropertyControls(FramerVMnGi0NIs, {
	variant: {
		options: ["H1zMAcI_H", "ax1zjzShX", "Pt4KWfrzS"],
		optionTitles: ["Variant 1", "Variant 2", "Variant 3"],
		title: "Variant",
		type: ControlType.Enum,
	},
	AU3sHoeBe: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	eRPXAioTG: {
		defaultValue: "2022-04-08T00:00:00.000Z",
		title: "Date",
		type: ControlType.Date,
	},
	RYVwbPoS8: {
		defaultValue: "latest post",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	Z1PV50RCS: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerVMnGi0NIs,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...GrainFonts,
		...AimFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:post
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Pt4KWfrzS",
	"2xl": "H1zMAcI_H",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PostFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var post_default = ComponentWithRoot;
export { post_default as default };
