// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7b947833d2a6e6bc "nitro (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'desktop' | 'mobile' // Variant
 * year?: string // year
 * company?: string // company
 * role?: string // role
 * description?: string // description
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-7JGR5MG2.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-KQJZ5C44.js";
import { stdin_default } from "./chunks/chunk-2FJHF24R.js";
import { className, css, fonts } from "./chunks/chunk-EGECXSOW.js";
import { routes } from "./chunks/chunk-UZPGWJTJ.js";

// virtual:process-step
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/bIU6Oqa7y9sdFL1JCVRx/jqYgWUH4UWWX0wzvzW7D/WZGKJ7sR1.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var AimFonts = getFonts(stdin_default);
var cycleOrder = ["jZzkIx5yL", "uwL5JZ9Pp"];
var serializationHash = "framer-RDLkl";
var variantClassNames = {
	jZzkIx5yL: "framer-v-stdd8n",
	uwL5JZ9Pp: "framer-v-k8ltqu",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	desktop: "jZzkIx5yL",
	mobile: "uwL5JZ9Pp",
};
var getProps = ({
	company,
	description,
	height,
	id,
	role,
	width,
	year,
	...props
}) => {
	return {
		...props,
		LxqEY5U_v:
			description ??
			props.LxqEY5U_v ??
			"We detect the real needs of your business and check the overall situation on the market.",
		MFpr9Rw9d: year ?? props.MFpr9Rw9d ?? "01",
		NBq5P6c5Y: company ?? props.NBq5P6c5Y ?? "Discovery",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "jZzkIx5yL",
		zuKjZpiSD: role ?? props.zuKjZpiSD ?? "Why are we doing that?",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		MFpr9Rw9d,
		NBq5P6c5Y,
		zuKjZpiSD,
		LxqEY5U_v,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "jZzkIx5yL",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className3, className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "uwL5JZ9Pp") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-stdd8n",
							className4,
							classNames,
						)}
						data-framer-name={"desktop"}
						layoutDependency={layoutDependency}
						layoutId={"jZzkIx5yL"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								uwL5JZ9Pp: {
									"data-framer-name": "mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-19mtlot"}
							data-framer-name={"Top Row"}
							layoutDependency={layoutDependency}
							layoutId={"Wn1EBKB0f"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1y5itb9"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"fMcUnUrX1"}
								style={{
									"--extracted-a0htzi":
										"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={MFpr9Rw9d}
								variants={{
									uwL5JZ9Pp: {
										"--extracted-r6o4lv":
											"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										uwL5JZ9Pp: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1i4mbrj"}
														data-styles-preset={"s0y5Rymtd"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
														}}
													>
														{"01"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-12lj5ox"}
										data-styles-preset={"YckFIlg3V"}
										style={{
											"--framer-text-color":
												"var(--extracted-a0htzi, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
										}}
									>
										{"01"}
									</motion.h3>
								</React.Fragment>
							</RichText>
							{isDisplayed() && (
								<motion.div
									className={"framer-16n0cnn"}
									data-framer-name={"Filler"}
									layoutDependency={layoutDependency}
									layoutId={"kMellbI7g"}
								/>
							)}
							<motion.div
								className={"framer-9vwong"}
								data-framer-name={"Heading Content"}
								layoutDependency={layoutDependency}
								layoutId={"dC37g4RHp"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1sv1t2b"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"e4d6LlNFW"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={NBq5P6c5Y}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h3
											className={"framer-styles-preset-12lj5ox"}
											data-styles-preset={"YckFIlg3V"}
										>
											{"Discovery"}
										</motion.h3>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-7owoix"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"G5zaCQWQW"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={zuKjZpiSD}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-21ogod"}
											data-styles-preset={"xZndidUCt"}
										>
											{"Why are we doing that?"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							{isDisplayed() && (
								<motion.div
									className={"framer-1jwczxv"}
									data-framer-name={"Filler"}
									layoutDependency={layoutDependency}
									layoutId={"rS9xlM49X"}
								/>
							)}
							<motion.div
								className={"framer-1kdfquu"}
								data-framer-name={"Text Content"}
								layoutDependency={layoutDependency}
								layoutId={"dvdYAb0t2"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-5ljgq5"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"PvtGYyNRV"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={LxqEY5U_v}
									variants={{
										uwL5JZ9Pp: {
											"--extracted-r6o4lv":
												"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											uwL5JZ9Pp: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-21ogod"}
															data-styles-preset={"xZndidUCt"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
															}}
														>
															{
																"We detect the real needs of your business and check the overall situation on the market."
															}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-21ogod"}
											data-styles-preset={"xZndidUCt"}
										>
											{
												"We detect the real needs of your business and check the overall situation on the market."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-y52j20"}
							data-framer-name={"Bottom Row"}
							layoutDependency={layoutDependency}
							layoutId={"Ihp8zRWJd"}
						>
							<motion.div
								className={"framer-2ms5bl"}
								layoutDependency={layoutDependency}
								layoutId={"Qs9snHRW1"}
								style={{
									backgroundColor:
										"var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25))",
								}}
							/>
							<motion.div
								className={"framer-131q0za"}
								data-framer-name={"Aim Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"EHwt_8V4u"}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-ofl2ay-container"}
										layoutDependency={layoutDependency}
										layoutId={"FBARTQODQ-container"}
										nodeId={"FBARTQODQ"}
										rendersWithMotion={true}
										scopeId={"WZGKJ7sR1"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "FBARTQODQ",
											layoutId: "FBARTQODQ",
											variant: "YnXfrsvOD",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-RDLkl.framer-5wnw2r, .framer-RDLkl .framer-5wnw2r { display: block; }",
	".framer-RDLkl.framer-stdd8n { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1200px; }",
	".framer-RDLkl .framer-19mtlot { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-RDLkl .framer-1y5itb9 { flex: 2 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-RDLkl .framer-16n0cnn { flex: 1 0 0px; height: 84px; overflow: hidden; position: relative; width: 1px; }",
	".framer-RDLkl .framer-9vwong { align-content: center; align-items: center; display: flex; flex: 2 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-RDLkl .framer-1sv1t2b, .framer-RDLkl .framer-7owoix, .framer-RDLkl .framer-5ljgq5 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-RDLkl .framer-1jwczxv { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 84px; justify-content: flex-start; overflow: hidden; padding: 24px 0px 0px 0px; position: relative; width: 1px; }",
	".framer-RDLkl .framer-1kdfquu { align-content: center; align-items: center; display: flex; flex: 2 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-RDLkl .framer-y52j20 { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-RDLkl .framer-2ms5bl { flex: 3 0 0px; height: 1px; overflow: visible; position: relative; width: 1px; }",
	".framer-RDLkl .framer-131q0za { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 36px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-RDLkl .framer-ofl2ay-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-RDLkl.framer-v-k8ltqu.framer-stdd8n { gap: 24px; width: 462px; }",
	".framer-RDLkl.framer-v-k8ltqu .framer-19mtlot { flex-direction: column; gap: 24px; }",
	".framer-RDLkl.framer-v-k8ltqu .framer-1y5itb9, .framer-RDLkl.framer-v-k8ltqu .framer-9vwong, .framer-RDLkl.framer-v-k8ltqu .framer-1kdfquu { flex: none; width: 100%; }",
	...css3,
	...css,
	...css2,
];
var FramerWZGKJ7sR1 = withCSS(Component, css4, "framer-RDLkl");
var stdin_default2 = FramerWZGKJ7sR1;
FramerWZGKJ7sR1.displayName = "Process Step";
FramerWZGKJ7sR1.defaultProps = {
	height: 156,
	width: 1200,
};
addPropertyControls(FramerWZGKJ7sR1, {
	variant: {
		options: ["jZzkIx5yL", "uwL5JZ9Pp"],
		optionTitles: ["desktop", "mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	MFpr9Rw9d: {
		defaultValue: "01",
		displayTextArea: false,
		title: "year",
		type: ControlType.String,
	},
	NBq5P6c5Y: {
		defaultValue: "Discovery",
		displayTextArea: false,
		title: "company",
		type: ControlType.String,
	},
	zuKjZpiSD: {
		defaultValue: "Why are we doing that?",
		displayTextArea: false,
		title: "role",
		type: ControlType.String,
	},
	LxqEY5U_v: {
		defaultValue:
			"We detect the real needs of your business and check the overall situation on the market.",
		displayTextArea: false,
		title: "description",
		type: ControlType.String,
	},
});
addFonts(
	FramerWZGKJ7sR1,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...AimFonts,
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:process-step
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "uwL5JZ9Pp",
	xl: "jZzkIx5yL",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProcessStepFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var process_step_default = ComponentWithRoot;
export { process_step_default as default };
