// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7b947833d2a6e6bc "nitro (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // title
 * category?: string // category
 * cardBackground?: string // card background
 * imgBackground?: string // img background
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * textColor?: string // text color
 * link?: string // Link
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-KQJZ5C44.js";
import { Icon } from "./chunks/chunk-KD6F3UC3.js";
import { className, css, fonts } from "./chunks/chunk-EGECXSOW.js";
import "./chunks/chunk-HR56UER2.js";
import { routes } from "./chunks/chunk-UZPGWJTJ.js";

// virtual:project-preview
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/7b35lRvGMshjB9E3KFbe/iMTbiALvUQdjhooehbzH/JsMvgH7oG.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MaterialFonts = getFonts(Icon);
var enabledGestures = {
	IUCH8Bd3E: {
		hover: true,
	},
};
var serializationHash = "framer-MilY6";
var variantClassNames = {
	IUCH8Bd3E: "framer-v-17p9bqe",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	cardBackground,
	category,
	height,
	id,
	image,
	imgBackground,
	link,
	textColor,
	title,
	width,
	...props
}) => {
	return {
		...props,
		CiAlhkexL:
			cardBackground ??
			props.CiAlhkexL ??
			"var(--token-bff440f0-6191-4f8e-b075-e48213673f37, rgb(255, 98, 0))",
		mVehmCS7W: category ?? props.mVehmCS7W ?? "bizzbuzz",
		NfFAAJ9Uk:
			textColor ??
			props.NfFAAJ9Uk ??
			"var(--token-b0ed99f9-6fa0-4e1a-bf69-922b8104b9bb, rgb(0, 0, 0))",
		NtbgtL9lU:
			imgBackground ??
			props.NtbgtL9lU ??
			"var(--token-33d35694-b896-43ea-b3a4-8d908d4a92c6, rgb(240, 84, 0))",
		qDYcPO5yw: link ?? props.qDYcPO5yw,
		xOdaJPMiZ: image ?? props.xOdaJPMiZ,
		xtGBSY9NN: title ?? props.xtGBSY9NN ?? "bizzbuzz",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		xtGBSY9NN,
		mVehmCS7W,
		CiAlhkexL,
		NtbgtL9lU,
		xOdaJPMiZ,
		NfFAAJ9Uk,
		qDYcPO5yw,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "IUCH8Bd3E",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={qDYcPO5yw}
						motionChild={true}
						nodeId={"IUCH8Bd3E"}
						scopeId={"JsMvgH7oG"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-17p9bqe", className3, classNames)} framer-1h0ue63`}
							data-framer-name={"Variant 1"}
							layoutDependency={layoutDependency}
							layoutId={"IUCH8Bd3E"}
							ref={refBinding}
							style={{
								backgroundColor: CiAlhkexL,
								borderBottomLeftRadius: 2,
								borderBottomRightRadius: 2,
								borderTopLeftRadius: 2,
								borderTopRightRadius: 2,
								...style,
							}}
							{...addPropertyOverrides(
								{
									"IUCH8Bd3E-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-bj7x6j"}
								data-framer-name={"Image Container"}
								layoutDependency={layoutDependency}
								layoutId={"oD6GdyRls"}
								style={{
									backgroundColor: NtbgtL9lU,
									borderBottomLeftRadius: 1,
									borderBottomRightRadius: 1,
									borderTopLeftRadius: 1,
									borderTopRightRadius: 1,
								}}
							>
								<motion.div
									className={"framer-1wop75a"}
									data-framer-name={"Image Content"}
									layoutDependency={layoutDependency}
									layoutId={"W0LlyYiEG"}
								>
									<Image
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 107.5) -
															0 -
															((componentViewport?.height || 107.5) - 0) * 1) /
															2) +
													(0 +
														(((componentViewport?.height || 107.5) - 0) * 1 -
															0 -
															(((componentViewport?.height || 107.5) - 0) * 1 -
																0) *
																1) /
															2) +
													(8 +
														((((componentViewport?.height || 107.5) - 0) * 1 -
															0) *
															1 -
															16 -
															((((componentViewport?.height || 107.5) - 0) * 1 -
																0) *
																1 -
																16) *
																1) /
															2),
											),
											sizes: `max(max(${componentViewport?.width || "100vw"} / 4, 1px) - 16px, 1px)`,
											...toResponsiveImage(xOdaJPMiZ),
										}}
										className={"framer-1vek4y4"}
										layoutDependency={layoutDependency}
										layoutId={"Nh_NSppdH"}
										style={{
											filter: "none",
											WebkitFilter: "none",
										}}
										variants={{
											"IUCH8Bd3E-hover": {
												filter: "grayscale(0)",
												WebkitFilter: "grayscale(0)",
											},
										}}
									/>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-k7yg3q"}
								data-framer-name={"Text Container"}
								layoutDependency={layoutDependency}
								layoutId={"lmUA8Kd88"}
							>
								<motion.div
									className={"framer-aisaaj"}
									data-framer-name={"Text Content"}
									layoutDependency={layoutDependency}
									layoutId={"PmUzkQrnD"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-st0845"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"DW1Yib4tT"}
										style={{
											"--extracted-r6o4lv":
												"var(--variable-reference-NfFAAJ9Uk-JsMvgH7oG)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
											"--variable-reference-NfFAAJ9Uk-JsMvgH7oG": NfFAAJ9Uk,
											opacity: 0.75,
										}}
										text={mVehmCS7W}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1i4mbrj"}
												data-styles-preset={"s0y5Rymtd"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--variable-reference-NfFAAJ9Uk-JsMvgH7oG))",
												}}
											>
												{"bizzbuzz"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-34tbce"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"IiW1MeaTG"}
										style={{
											"--extracted-a0htzi":
												"var(--variable-reference-NfFAAJ9Uk-JsMvgH7oG)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
											"--variable-reference-NfFAAJ9Uk-JsMvgH7oG": NfFAAJ9Uk,
										}}
										text={xtGBSY9NN}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.h3
												className={"framer-styles-preset-12lj5ox"}
												data-styles-preset={"YckFIlg3V"}
												style={{
													"--framer-text-color":
														"var(--extracted-a0htzi, var(--variable-reference-NfFAAJ9Uk-JsMvgH7oG))",
												}}
											>
												{"bizzbuzz"}
											</motion.h3>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-1o60ytk"}
									data-framer-name={"Arrow Wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"AQW74goPW"}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-x2meqd-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"koCpYAN7B-container"}
											nodeId={"koCpYAN7B"}
											rendersWithMotion={true}
											scopeId={"JsMvgH7oG"}
											style={{
												opacity: 0.5,
												rotate: -45,
											}}
											variants={{
												"IUCH8Bd3E-hover": {
													opacity: 1,
													rotate: 0,
												},
											}}
										>
											<Icon
												color={NfFAAJ9Uk}
												height={"100%"}
												iconSearch={"Home"}
												iconSelection={"ArrowForward"}
												iconStyle15={"Filled"}
												iconStyle2={"Filled"}
												iconStyle7={"Filled"}
												id={"koCpYAN7B"}
												layoutId={"koCpYAN7B"}
												mirrored={false}
												selectByList={true}
												style={{
													height: "100%",
													width: "100%",
												}}
												width={"100%"}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-MilY6.framer-1h0ue63, .framer-MilY6 .framer-1h0ue63 { display: block; }",
	".framer-MilY6.framer-17p9bqe { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 1200px; will-change: var(--framer-will-change-override, transform); }",
	".framer-MilY6 .framer-bj7x6j { align-content: center; align-items: center; align-self: stretch; display: flex; flex: 2 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: auto; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-MilY6 .framer-1wop75a { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; overflow: visible; padding: 8px; position: relative; width: 1px; }",
	".framer-MilY6 .framer-1vek4y4 { flex: 1 0 0px; height: 100%; overflow: visible; position: relative; width: 1px; }",
	".framer-MilY6 .framer-k7yg3q { align-content: center; align-items: center; display: flex; flex: 6 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-MilY6 .framer-aisaaj { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 16px; position: relative; width: 1px; }",
	".framer-MilY6 .framer-st0845, .framer-MilY6 .framer-34tbce { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-MilY6 .framer-1o60ytk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 48px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 48px; }",
	".framer-MilY6 .framer-x2meqd-container { flex: none; height: 36px; position: relative; width: 36px; }",
	...css,
	...css2,
];
var FramerJsMvgH7oG = withCSS(Component, css3, "framer-MilY6");
var stdin_default = FramerJsMvgH7oG;
FramerJsMvgH7oG.displayName = "project preview";
FramerJsMvgH7oG.defaultProps = {
	height: 107.5,
	width: 1200,
};
addPropertyControls(FramerJsMvgH7oG, {
	xtGBSY9NN: {
		defaultValue: "bizzbuzz",
		displayTextArea: false,
		title: "title",
		type: ControlType.String,
	},
	mVehmCS7W: {
		defaultValue: "bizzbuzz",
		displayTextArea: false,
		title: "category",
		type: ControlType.String,
	},
	CiAlhkexL: {
		defaultValue:
			'var(--token-bff440f0-6191-4f8e-b075-e48213673f37, rgb(255, 98, 0)) /* {"name":"card 1 bg"} */',
		title: "card background",
		type: ControlType.Color,
	},
	NtbgtL9lU: {
		defaultValue:
			'var(--token-33d35694-b896-43ea-b3a4-8d908d4a92c6, rgb(240, 84, 0)) /* {"name":"card 1 img"} */',
		title: "img background",
		type: ControlType.Color,
	},
	xOdaJPMiZ: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	NfFAAJ9Uk: {
		defaultValue:
			"var(--token-b0ed99f9-6fa0-4e1a-bf69-922b8104b9bb, rgb(0, 0, 0))",
		title: "text color",
		type: ControlType.Color,
	},
	qDYcPO5yw: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerJsMvgH7oG,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...MaterialFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:project-preview
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProjectPreviewFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var project_preview_default = ComponentWithRoot;
export { project_preview_default as default };
