// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7b947833d2a6e6bc "nitro (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'd1' | 'd2' | 'd3' | 'd4' | 'l1' | 'l2' | 'l3' | 'l4' | 't1' | 't2' | 't3' | 't4' | 'm1' | 'm2' | 'm3' | 'm4' // Variant
 * _1?: string // 1
 * _2?: string // 2
 * _3?: string // 3
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-XR7KURMW.js";
import { routes } from "./chunks/chunk-UZPGWJTJ.js";

// virtual:text-slider
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/iZ7bQOr7hgeEKbsXdYrS/dTg6XGzYEYSshjCqbanM/v0epBcyaR.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = [
	"RiboSqWn2",
	"BG8c4Nkkd",
	"PH0XFLhmp",
	"MrLHJRgcN",
	"GeEppSKMT",
	"u2IsWExqY",
	"E5WqOqbWP",
	"JCR8k4ZvQ",
	"PeGUsZVKa",
	"gzDLpJe2P",
	"GkkZY4SQp",
	"GSBPqzC15",
	"T7BSV53Dd",
	"khltgVggC",
	"B2XXZN65q",
	"rupA0W6WE",
];
var serializationHash = "framer-SXeci";
var variantClassNames = {
	B2XXZN65q: "framer-v-1piyyuf",
	BG8c4Nkkd: "framer-v-1hcgehd",
	E5WqOqbWP: "framer-v-pmtk02",
	GeEppSKMT: "framer-v-ttpppc",
	GkkZY4SQp: "framer-v-7aafhn",
	GSBPqzC15: "framer-v-1855qvm",
	gzDLpJe2P: "framer-v-1lywwwe",
	JCR8k4ZvQ: "framer-v-7irn0s",
	khltgVggC: "framer-v-g2f0ia",
	MrLHJRgcN: "framer-v-1tl009w",
	PeGUsZVKa: "framer-v-9bt7hr",
	PH0XFLhmp: "framer-v-16cp40x",
	RiboSqWn2: "framer-v-1dog2b1",
	rupA0W6WE: "framer-v-1n4j2t1",
	T7BSV53Dd: "framer-v-lkmqeq",
	u2IsWExqY: "framer-v-1excvc3",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	duration: 0,
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 0.3,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	d1: "RiboSqWn2",
	d2: "BG8c4Nkkd",
	d3: "PH0XFLhmp",
	d4: "MrLHJRgcN",
	l1: "GeEppSKMT",
	l2: "u2IsWExqY",
	l3: "E5WqOqbWP",
	l4: "JCR8k4ZvQ",
	m1: "T7BSV53Dd",
	m2: "khltgVggC",
	m3: "B2XXZN65q",
	m4: "rupA0W6WE",
	t1: "PeGUsZVKa",
	t2: "gzDLpJe2P",
	t3: "GkkZY4SQp",
	t4: "GSBPqzC15",
};
var getProps = ({ _1, _2, _3, height, id, width, ...props }) => {
	return {
		...props,
		botQQk8dc: _3 ?? props.botQQk8dc ?? "interactive experiences",
		JPARd711g: _2 ?? props.JPARd711g ?? "software interfaces",
		uW8HcBa0c: _1 ?? props.uW8HcBa0c ?? "no-code websites",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "RiboSqWn2",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		uW8HcBa0c: uW8HcBa0c2,
		JPARd711g: JPARd711g2,
		botQQk8dc: botQQk8dc2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "RiboSqWn2",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear1mza1kw = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("BG8c4Nkkd"), 1e3);
	});
	const onAppear1n8bzsw = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("PH0XFLhmp"), 2e3);
	});
	const onAppear1x01461 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("MrLHJRgcN"), 2e3);
	});
	const onAppear1woba31 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("RiboSqWn2"), 1e3);
	});
	const onAppear1dclgo9 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("u2IsWExqY"), 1e3);
	});
	const onAppear1ltbukk = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("E5WqOqbWP"), 2e3);
	});
	const onAppear1l7ci2w = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("JCR8k4ZvQ"), 2e3);
	});
	const onAppear1svwtsv = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("GeEppSKMT"), 1e3);
	});
	const onAppear79d2nx = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("gzDLpJe2P"), 1e3);
	});
	const onAppear1iiuwnj = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("GkkZY4SQp"), 2e3);
	});
	const onAppear1frp0o9 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("GSBPqzC15"), 2e3);
	});
	const onAppear1f4nwlb = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("PeGUsZVKa"), 1e3);
	});
	const onAppear1k7zo6h = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("T7BSV53Dd"), 1e3);
	});
	const onAppear12uw7kn = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("B2XXZN65q"), 2e3);
	});
	const onAppearr2jx64 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("rupA0W6WE"), 2e3);
	});
	useOnVariantChange(baseVariant, {
		B2XXZN65q: onAppearr2jx64,
		BG8c4Nkkd: onAppear1n8bzsw,
		default: onAppear1mza1kw,
		E5WqOqbWP: onAppear1l7ci2w,
		GeEppSKMT: onAppear1dclgo9,
		GkkZY4SQp: onAppear1frp0o9,
		GSBPqzC15: onAppear1f4nwlb,
		gzDLpJe2P: onAppear1iiuwnj,
		JCR8k4ZvQ: onAppear1svwtsv,
		khltgVggC: onAppear12uw7kn,
		MrLHJRgcN: onAppear1woba31,
		PeGUsZVKa: onAppear79d2nx,
		PH0XFLhmp: onAppear1x01461,
		rupA0W6WE: onAppear1k7zo6h,
		T7BSV53Dd: onAppear1k7zo6h,
		u2IsWExqY: onAppear1ltbukk,
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							B2XXZN65q: {
								value: transition2,
							},
							BG8c4Nkkd: {
								value: transition2,
							},
							E5WqOqbWP: {
								value: transition2,
							},
							GkkZY4SQp: {
								value: transition2,
							},
							GSBPqzC15: {
								value: transition2,
							},
							gzDLpJe2P: {
								value: transition2,
							},
							JCR8k4ZvQ: {
								value: transition2,
							},
							khltgVggC: {
								value: transition2,
							},
							MrLHJRgcN: {
								value: transition2,
							},
							PH0XFLhmp: {
								value: transition2,
							},
							rupA0W6WE: {
								value: transition2,
							},
							u2IsWExqY: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1dog2b1",
							className2,
							classNames,
						)}
						data-framer-name={"d1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"RiboSqWn2"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								B2XXZN65q: {
									"data-framer-name": "m3",
								},
								BG8c4Nkkd: {
									"data-framer-name": "d2",
								},
								E5WqOqbWP: {
									"data-framer-name": "l3",
								},
								GeEppSKMT: {
									"data-framer-name": "l1",
								},
								GkkZY4SQp: {
									"data-framer-name": "t3",
								},
								GSBPqzC15: {
									"data-framer-name": "t4",
								},
								gzDLpJe2P: {
									"data-framer-name": "t2",
								},
								JCR8k4ZvQ: {
									"data-framer-name": "l4",
								},
								khltgVggC: {
									"data-framer-name": "m2",
								},
								MrLHJRgcN: {
									"data-framer-name": "d4",
								},
								PeGUsZVKa: {
									"data-framer-name": "t1",
								},
								PH0XFLhmp: {
									"data-framer-name": "d3",
								},
								rupA0W6WE: {
									"data-framer-name": "m4",
								},
								T7BSV53Dd: {
									"data-framer-name": "m1",
								},
								u2IsWExqY: {
									"data-framer-name": "l2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-8g5f1i"}
							layoutDependency={layoutDependency}
							layoutId={"Y8ZxG8DqC"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-b8t0e"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"bD4L42J_O"}
								style={{
									"--extracted-gdpscs": "rgb(255, 255, 255)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 1,
								}}
								text={uW8HcBa0c2}
								variants={{
									B2XXZN65q: {
										opacity: 0,
									},
									BG8c4Nkkd: {
										opacity: 0,
									},
									E5WqOqbWP: {
										opacity: 0,
									},
									GeEppSKMT: {
										opacity: 1,
									},
									GkkZY4SQp: {
										opacity: 0,
									},
									GSBPqzC15: {
										opacity: 1,
									},
									gzDLpJe2P: {
										opacity: 0,
									},
									JCR8k4ZvQ: {
										opacity: 1,
									},
									khltgVggC: {
										opacity: 0,
									},
									MrLHJRgcN: {
										opacity: 1,
									},
									PeGUsZVKa: {
										opacity: 1,
									},
									PH0XFLhmp: {
										opacity: 0,
									},
									rupA0W6WE: {
										opacity: 1,
									},
									T7BSV53Dd: {
										opacity: 1,
									},
									u2IsWExqY: {
										opacity: 0,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h1
										className={"framer-styles-preset-3nqyhf"}
										data-styles-preset={"YAP816Y5n"}
										style={{
											"--framer-text-color":
												"var(--extracted-gdpscs, rgb(255, 255, 255))",
										}}
									>
										{"no-code websites"}
									</motion.h1>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1o6qnwd"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"mxZZ4RmYn"}
								style={{
									"--extracted-gdpscs": "rgb(255, 255, 255)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 0,
								}}
								text={JPARd711g2}
								variants={{
									BG8c4Nkkd: {
										opacity: 1,
									},
									gzDLpJe2P: {
										opacity: 1,
									},
									khltgVggC: {
										opacity: 1,
									},
									u2IsWExqY: {
										opacity: 1,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h1
										className={"framer-styles-preset-3nqyhf"}
										data-styles-preset={"YAP816Y5n"}
										style={{
											"--framer-text-color":
												"var(--extracted-gdpscs, rgb(255, 255, 255))",
										}}
									>
										{"software interfaces"}
									</motion.h1>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-78djsk"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"MuQgfIqhB"}
								style={{
									"--extracted-gdpscs": "rgb(255, 255, 255)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 0,
								}}
								text={botQQk8dc2}
								variants={{
									B2XXZN65q: {
										opacity: 1,
									},
									E5WqOqbWP: {
										opacity: 1,
									},
									GkkZY4SQp: {
										opacity: 1,
									},
									PH0XFLhmp: {
										opacity: 1,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h1
										className={"framer-styles-preset-3nqyhf"}
										data-styles-preset={"YAP816Y5n"}
										style={{
											"--framer-text-color":
												"var(--extracted-gdpscs, rgb(255, 255, 255))",
										}}
									>
										{"interactive experiences"}
									</motion.h1>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-111b39f"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"zlw3EbaoD"}
								style={{
									"--extracted-gdpscs": "rgb(255, 255, 255)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 1,
								}}
								text={uW8HcBa0c2}
								variants={{
									B2XXZN65q: {
										opacity: 0,
									},
									BG8c4Nkkd: {
										opacity: 0,
									},
									E5WqOqbWP: {
										opacity: 0,
									},
									GeEppSKMT: {
										opacity: 1,
									},
									GkkZY4SQp: {
										opacity: 0,
									},
									GSBPqzC15: {
										opacity: 1,
									},
									gzDLpJe2P: {
										opacity: 0,
									},
									JCR8k4ZvQ: {
										opacity: 1,
									},
									khltgVggC: {
										opacity: 0,
									},
									MrLHJRgcN: {
										opacity: 1,
									},
									PeGUsZVKa: {
										opacity: 1,
									},
									PH0XFLhmp: {
										opacity: 0,
									},
									rupA0W6WE: {
										opacity: 1,
									},
									T7BSV53Dd: {
										opacity: 1,
									},
									u2IsWExqY: {
										opacity: 0,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h1
										className={"framer-styles-preset-3nqyhf"}
										data-styles-preset={"YAP816Y5n"}
										style={{
											"--framer-text-color":
												"var(--extracted-gdpscs, rgb(255, 255, 255))",
										}}
									>
										{"no-code websites"}
									</motion.h1>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-SXeci.framer-1baggof, .framer-SXeci .framer-1baggof { display: block; }",
	".framer-SXeci.framer-1dog2b1 { gap: 0px; height: 130px; overflow: hidden; position: relative; width: 1154px; }",
	".framer-SXeci .framer-8g5f1i { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 0px; overflow: visible; padding: 0px; position: absolute; top: 0px; width: min-content; }",
	".framer-SXeci .framer-b8t0e, .framer-SXeci .framer-1o6qnwd, .framer-SXeci .framer-78djsk, .framer-SXeci .framer-111b39f { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 1154px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-SXeci.framer-v-1hcgehd .framer-8g5f1i { top: -130px; }",
	".framer-SXeci.framer-v-16cp40x .framer-8g5f1i { top: -260px; }",
	".framer-SXeci.framer-v-1tl009w .framer-8g5f1i { top: -390px; }",
	".framer-SXeci.framer-v-ttpppc.framer-1dog2b1, .framer-SXeci.framer-v-1excvc3.framer-1dog2b1, .framer-SXeci.framer-v-pmtk02.framer-1dog2b1, .framer-SXeci.framer-v-7irn0s.framer-1dog2b1 { height: 100px; }",
	".framer-SXeci.framer-v-1excvc3 .framer-8g5f1i { top: -100px; }",
	".framer-SXeci.framer-v-pmtk02 .framer-8g5f1i { top: -200px; }",
	".framer-SXeci.framer-v-7irn0s .framer-8g5f1i { top: -300px; }",
	".framer-SXeci.framer-v-9bt7hr.framer-1dog2b1, .framer-SXeci.framer-v-1lywwwe.framer-1dog2b1, .framer-SXeci.framer-v-7aafhn.framer-1dog2b1, .framer-SXeci.framer-v-1855qvm.framer-1dog2b1 { height: 75px; }",
	".framer-SXeci.framer-v-1lywwwe .framer-8g5f1i { top: -75px; }",
	".framer-SXeci.framer-v-7aafhn .framer-8g5f1i { top: -150px; }",
	".framer-SXeci.framer-v-1855qvm .framer-8g5f1i { top: -225px; }",
	".framer-SXeci.framer-v-lkmqeq.framer-1dog2b1, .framer-SXeci.framer-v-g2f0ia.framer-1dog2b1, .framer-SXeci.framer-v-1piyyuf.framer-1dog2b1, .framer-SXeci.framer-v-1n4j2t1.framer-1dog2b1 { height: 45px; }",
	".framer-SXeci.framer-v-g2f0ia .framer-8g5f1i { top: -45px; }",
	".framer-SXeci.framer-v-1piyyuf .framer-8g5f1i { top: -90px; }",
	".framer-SXeci.framer-v-1n4j2t1 .framer-8g5f1i { top: -135px; }",
	...css,
];
var Framerv0epBcyaR = withCSS(Component, css2, "framer-SXeci");
var stdin_default = Framerv0epBcyaR;
Framerv0epBcyaR.displayName = "text slider";
Framerv0epBcyaR.defaultProps = {
	height: 130,
	width: 1154,
};
addPropertyControls(Framerv0epBcyaR, {
	variant: {
		options: [
			"RiboSqWn2",
			"BG8c4Nkkd",
			"PH0XFLhmp",
			"MrLHJRgcN",
			"GeEppSKMT",
			"u2IsWExqY",
			"E5WqOqbWP",
			"JCR8k4ZvQ",
			"PeGUsZVKa",
			"gzDLpJe2P",
			"GkkZY4SQp",
			"GSBPqzC15",
			"T7BSV53Dd",
			"khltgVggC",
			"B2XXZN65q",
			"rupA0W6WE",
		],
		optionTitles: [
			"d1",
			"d2",
			"d3",
			"d4",
			"l1",
			"l2",
			"l3",
			"l4",
			"t1",
			"t2",
			"t3",
			"t4",
			"m1",
			"m2",
			"m3",
			"m4",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	uW8HcBa0c: {
		defaultValue: "no-code websites",
		displayTextArea: false,
		title: "1",
		type: ControlType.String,
	},
	JPARd711g: {
		defaultValue: "software interfaces",
		displayTextArea: false,
		title: "2",
		type: ControlType.String,
	},
	botQQk8dc: {
		defaultValue: "interactive experiences",
		displayTextArea: false,
		title: "3",
		type: ControlType.String,
	},
});
addFonts(
	Framerv0epBcyaR,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:text-slider
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TextSliderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var text_slider_default = ComponentWithRoot;
export { text_slider_default as default };
