// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7b947833d2a6e6bc "nitro (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Grain } from "./chunks/chunk-J6FBOBB4.js";
import { stdin_default } from "./chunks/chunk-2FJHF24R.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-FCJZKTDO.js";
import { className, css, fonts } from "./chunks/chunk-EGECXSOW.js";
import { routes } from "./chunks/chunk-UZPGWJTJ.js";

// virtual:tool
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/l5li7ye638K74XaGLCge/UqEtsT3DESwMQq2SvTKl/hi6LURg6s.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var GrainFonts = getFonts(Grain);
var AimFonts = getFonts(stdin_default);
var enabledGestures = {
	ejXwuTR2B: {
		hover: true,
	},
};
var cycleOrder = ["ejXwuTR2B", "JOBmtjgpY"];
var serializationHash = "framer-kLXXm";
var variantClassNames = {
	ejXwuTR2B: "framer-v-vwwvmb",
	JOBmtjgpY: "framer-v-135pp80",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "ejXwuTR2B",
	"Variant 2": "JOBmtjgpY",
};
var getProps = ({ category, height, id, image, tool, width, ...props }) => {
	return {
		...props,
		JN95yfhUz: tool ?? props.JN95yfhUz ?? "Framer",
		rbjrvi7FU: image ?? props.rbjrvi7FU,
		sA3LlWG4k: category ?? props.sA3LlWG4k ?? "web design",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ejXwuTR2B",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		rbjrvi7FU,
		JN95yfhUz,
		sA3LlWG4k,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ejXwuTR2B",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "JOBmtjgpY") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-vwwvmb",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"ejXwuTR2B"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								"ejXwuTR2B-hover": {
									"data-framer-name": void 0,
								},
								JOBmtjgpY: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 0 + 0,
								),
								sizes: `calc(${componentViewport?.width || "100vw"} / 4)`,
								...toResponsiveImage(rbjrvi7FU),
							}}
							className={"framer-1sduvlg"}
							layoutDependency={layoutDependency}
							layoutId={"r5oziGPjL"}
							style={{
								borderBottomLeftRadius: 2,
								borderBottomRightRadius: 2,
								borderTopLeftRadius: 2,
								borderTopRightRadius: 2,
								filter: "grayscale(1)",
								opacity: 0.5,
								WebkitFilter: "grayscale(1)",
							}}
							variants={{
								"ejXwuTR2B-hover": {
									filter: "grayscale(0)",
									opacity: 1,
									WebkitFilter: "grayscale(0)",
								},
							}}
							{...addPropertyOverrides(
								{
									JOBmtjgpY: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													0 +
													((componentViewport?.height || 73) - 0 - 76),
											),
											sizes: `max(${componentViewport?.width || "100vw"} / 4, 1px)`,
											...toResponsiveImage(rbjrvi7FU),
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-x7r1sz-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"AbcI485cu-container"}
									nodeId={"AbcI485cu"}
									rendersWithMotion={true}
									scopeId={"hi6LURg6s"}
								>
									<Grain
										height={"100%"}
										id={"AbcI485cu"}
										layoutId={"AbcI485cu"}
										opacity={0.05}
										style={{
											height: "100%",
											width: "100%",
										}}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</Image>
						<motion.div
							className={"framer-k31nfp"}
							layoutDependency={layoutDependency}
							layoutId={"t9nIAXQuu"}
						>
							<motion.div
								className={"framer-1l31g06"}
								layoutDependency={layoutDependency}
								layoutId={"ZfpAgDNpD"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1ey32hl"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"AuF9BsIKs"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={JN95yfhUz}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-ugcj2n"}
											data-styles-preset={"JLUy8CuLJ"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
											}}
										>
											{"Framer"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1tmjo33"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"AzxYScDg9"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={sA3LlWG4k}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1i4mbrj"}
											data-styles-preset={"s0y5Rymtd"}
											style={{
												"--framer-text-alignment": "left",
											}}
										>
											{"web design"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-xzrvsr-container"}
									layoutDependency={layoutDependency}
									layoutId={"XikSgGMNp-container"}
									nodeId={"XikSgGMNp"}
									rendersWithMotion={true}
									scopeId={"hi6LURg6s"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "XikSgGMNp",
										layoutId: "XikSgGMNp",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "YnXfrsvOD",
										width: "100%",
										...addPropertyOverrides(
											{
												"ejXwuTR2B-hover": {
													variant: "gWsTOWKop",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
						{isDisplayed() && (
							<motion.div
								className={"framer-11vk8t0"}
								layoutDependency={layoutDependency}
								layoutId={"IG3s8r9Eb"}
							/>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kLXXm.framer-1y62ly9, .framer-kLXXm .framer-1y62ly9 { display: block; }",
	".framer-kLXXm.framer-vwwvmb { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 28px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1200px; }",
	".framer-kLXXm .framer-1sduvlg { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 300px); overflow: hidden; position: relative; width: 25%; will-change: var(--framer-will-change-override, transform); }",
	".framer-kLXXm .framer-x7r1sz-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; }",
	".framer-kLXXm .framer-k31nfp { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-kLXXm .framer-1l31g06 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-kLXXm .framer-1ey32hl, .framer-kLXXm .framer-1tmjo33 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-kLXXm .framer-xzrvsr-container { flex: none; height: 36px; position: relative; width: 36px; }",
	".framer-kLXXm .framer-11vk8t0 { flex: 1 0 0px; height: 1px; overflow: visible; position: relative; width: 100%; }",
	".framer-kLXXm.framer-v-135pp80.framer-vwwvmb { align-content: flex-end; align-items: flex-end; cursor: unset; flex-direction: row; gap: 0px; width: 290px; }",
	".framer-kLXXm.framer-v-135pp80 .framer-1sduvlg { flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 73px); order: 0; width: 1px; }",
	".framer-kLXXm.framer-v-135pp80 .framer-k31nfp { flex: 2 0 0px; gap: 16px; order: 2; width: 1px; }",
	".framer-kLXXm.framer-v-135pp80 .framer-11vk8t0 { align-self: stretch; height: auto; order: 1; width: 1px; }",
	...css2,
	...css,
];
var Framerhi6LURg6s = withCSS(Component, css3, "framer-kLXXm");
var stdin_default2 = Framerhi6LURg6s;
Framerhi6LURg6s.displayName = "tool";
Framerhi6LURg6s.defaultProps = {
	height: 381,
	width: 1200,
};
addPropertyControls(Framerhi6LURg6s, {
	variant: {
		options: ["ejXwuTR2B", "JOBmtjgpY"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
	rbjrvi7FU: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	JN95yfhUz: {
		defaultValue: "Framer",
		displayTextArea: false,
		title: "tool",
		type: ControlType.String,
	},
	sA3LlWG4k: {
		defaultValue: "web design",
		displayTextArea: false,
		title: "category",
		type: ControlType.String,
	},
});
addFonts(
	Framerhi6LURg6s,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...GrainFonts,
		...AimFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:tool
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "JOBmtjgpY",
	xl: "ejXwuTR2B",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ToolFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7b947833d2a6e6bc8ef537bf754afcefb3a24c5c4e74695fbe3bec6fdcab91e6"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var tool_default = ComponentWithRoot;
export { tool_default as default };
